//! OpenAPI aggregate for settings, vendor HTTP, and agent memory routes.

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(paths(
    crate::settings::dev::get_switch_ai_dev_tool,
    crate::settings::dev::put_switch_ai_dev_tool,
    crate::settings::about::post_check_update,
    crate::settings::about::post_download_app,
    crate::settings::help_hub::get_help_hub_links,
    crate::settings::help_hub::get_help_hub_config,
    crate::settings::help_hub::post_user_help_hub_links,
    crate::settings::help_hub::post_workspace_help_hub_links,
    crate::settings::notifications::get_notifications,
    crate::settings::notifications::mark_notifications_read,
    crate::settings::notifications::mark_all_notifications_read,
    crate::settings::notifications::delete_notifications,
    crate::settings::notifications::delete_read_notifications,
    crate::settings::notifications::get_notifications_preferences,
    crate::settings::notifications::get_notifications_preferences_export,
    crate::settings::notifications::post_notifications_preferences,
    crate::settings::notifications::post_notifications_preferences_import,
    crate::settings::notifications::post_notifications_preferences_apply_template,
    crate::settings::notifications::post_notifications_preferences_reset,
    crate::settings::platform_config::get_platform_config,
    crate::settings::platform_config::post_platform_config,
    crate::settings::outbound_webhooks::post_outbound_webhook_create,
    crate::settings::outbound_webhooks::get_outbound_webhook_list,
    crate::settings::outbound_webhooks::delete_outbound_webhook,
    crate::settings::outbound_webhooks::post_outbound_webhook_test,
    crate::settings::danger::post_delete_all_data,
    crate::settings::danger::post_clear_database,
    crate::settings::memory_config::get_memory_config,
    crate::settings::memory_config::post_memory_config,
    crate::settings::memory_config::post_clear_agent_memories_type_field_alias,
    crate::settings::agent_deploy::post_agent_deploy_list,
    crate::settings::agent_deploy::post_deploy_agent_model,
    crate::settings::agent_deploy::post_agent_set_key,
    crate::settings::vendors::handlers::summary::get_vendors_summary,
    crate::settings::vendors::handlers::model_test::post_vendor_model_test,
    crate::settings::vendors::handlers::vendor_manage::post_add_vendor,
    crate::settings::vendors::handlers::vendor_manage::post_update_vendor,
    crate::settings::vendors::handlers::vendor_manage::post_delete_vendor,
    crate::settings::vendors::handlers::vendor_manage::post_enable_vendor,
    crate::settings::vendors::handlers::vendor_manage::post_update_vendor_code,
    crate::settings::vendors::handlers::vendor_manage::post_vendor_code_from_link,
    crate::settings::vendors::handlers::credential::post_store_credential,
    crate::settings::vendors::handlers::credential::get_credential,
    crate::settings::vendors::handlers::credential::delete_credential,
    crate::settings::agent_memory::query_memory,
    crate::settings::agent_memory::clear_memory,
    crate::settings::agent_memory::append_memory,
))]
pub struct SettingsOpenApi;
