part of '../../../../home_page.dart';

extension _AssetGenerationWorkbenchDialogView
    on _AssetGenerationWorkbenchDialogState {
  AlertDialog _buildAssetGenerationWorkbenchDialogView({
    required BuildContext context,
    required List<AssetRow> visible,
    required List<AssetRow> scopedAssets,
    required Map<String, List<int>> typeSelections,
    required Map<String, List<int>> pollingSelections,
    required Map<String, List<int>> promptSelections,
    required List<int> selected,
    required int? selectedSingleAssetId,
    required int selectedScriptNumericId,
    required String selectedType,
    required bool loadingSummary,
    required bool busyMutation,
    required AssetsDataResponseV1? productionData,
    required AssetsPollingImageResponseV1? pollingData,
    required WorkbenchAssetMaterialDataResponse? materialData,
    required WorkbenchAssetBatchGenerationResponse? batchData,
    required List<WorkbenchAssetPollingPromptItem>? promptPollingData,
    required String? statusLine,
    required TextEditingController modelCtrl,
    required TextEditingController resolutionCtrl,
    required TextEditingController imageUrlCtrl,
    required TextEditingController batchNameCtrl,
    required TextEditingController batchLimitCtrl,
    required ValueChanged<int> onScriptChanged,
    required ValueChanged<String> onImageUrlChanged,
    required Future<void> Function(String nextType) onTypeChanged,
    required Future<void> Function() onSyncWorkbenchSnapshot,
    required Future<void> Function() onLoadMaterialContext,
    required Future<void> Function() onLoadBatchCandidates,
    required VoidCallback onSelectAllVisible,
    required VoidCallback onRebuildSelectionByType,
    required VoidCallback onClearSelection,
    required Future<void> Function() onBatchGenerateImages,
    required Future<void> Function() onPollImageStatuses,
    required Future<void> Function() onPollPromptStatuses,
    required Future<void> Function() onDeleteDerivatives,
    required Future<void> Function() onUpdateImageUrl,
    required void Function(String label, List<int> ids) onApplyPollingSelection,
    required VoidCallback onApplyMaterialSelection,
    required VoidCallback onApplyBatchSelection,
    required void Function(String label, List<int> ids) onApplyPromptSelection,
    required void Function(AssetRow asset, bool checked) onToggleAsset,
    required VoidCallback onClose,
  }) {
    return AlertDialog(
      title: const Text('资产出图工作台'),
      content: SizedBox(
        width: 860,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                '把 production 资产摘要、批量出图、状态轮询、衍生图清理和封面 URL 更新收口到项目资产主流程，不再只依赖 system probe。',
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  color: Theme.of(context).colorScheme.outline,
                ),
              ),
              const SizedBox(height: 12),
              _AssetGenerationControlsPanel(
                busy: busyMutation,
                scriptList: widget.scriptList,
                visibleAssets: visible,
                typeSelections: typeSelections,
                selectedScriptNumericId: selectedScriptNumericId,
                selectedType: selectedType,
                modelCtrl: modelCtrl,
                resolutionCtrl: resolutionCtrl,
                imageUrlCtrl: imageUrlCtrl,
                batchNameCtrl: batchNameCtrl,
                batchLimitCtrl: batchLimitCtrl,
                onScriptChanged: onScriptChanged,
                onImageUrlChanged: onImageUrlChanged,
                onTypeChanged: onTypeChanged,
              ),
              const SizedBox(height: 12),
              _AssetGenerationActionsPanel(
                loadingSummary: loadingSummary,
                busyMutation: busyMutation,
                visibleAssets: visible,
                scopedAssets: scopedAssets,
                typeSelections: typeSelections,
                selectedType: selectedType,
                selected: selected,
                selectedSingleAssetId: selectedSingleAssetId,
                imageUrlCtrl: imageUrlCtrl,
                onSyncWorkbenchSnapshot: onSyncWorkbenchSnapshot,
                onLoadMaterialContext: onLoadMaterialContext,
                onLoadBatchCandidates: onLoadBatchCandidates,
                onSelectAllVisible: onSelectAllVisible,
                onRebuildSelectionByType: onRebuildSelectionByType,
                onClearSelection: onClearSelection,
                onBatchGenerateImages: onBatchGenerateImages,
                onPollImageStatuses: onPollImageStatuses,
                onPollPromptStatuses: onPollPromptStatuses,
                onDeleteDerivatives: onDeleteDerivatives,
                onUpdateImageUrl: onUpdateImageUrl,
              ),
              const SizedBox(height: 8),
              _AssetGenerationStatusPanel(
                busy: busyMutation,
                statusLine: statusLine,
                productionData: productionData,
                pollingData: pollingData,
                materialData: materialData,
                batchData: batchData,
                promptPollingData: promptPollingData,
                pollingSelections: pollingSelections,
                promptSelections: promptSelections,
                onApplyPollingSelection: onApplyPollingSelection,
                onApplyMaterialSelection: onApplyMaterialSelection,
                onApplyBatchSelection: onApplyBatchSelection,
                onApplyPromptSelection: onApplyPromptSelection,
              ),
              _AssetGenerationSelectionPanel(
                busy: busyMutation,
                filterScriptNumericId: widget.assetsFilterScriptNumericId[0],
                scopedAssets: scopedAssets,
                selectedIds: _selectedIds,
                onToggleAsset: onToggleAsset,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: busyMutation ? null : onClose,
          child: const Text('关闭'),
        ),
      ],
    );
  }
}
