#!/usr/bin/env python3
"""
Refactor view.dart into 8 modules using part/part of pattern.
Keeps data models and helper widgets in main file, extracts large UI sections.
"""

# Read the original file
with open('frontend/lib/short_video_space/view.dart', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the start of ShortVideoSpaceView class
view_class_start = None
for i, line in enumerate(lines):
    if 'class ShortVideoSpaceView extends StatelessWidget' in line:
        view_class_start = i
        break

# Find the build method start
build_start = None
for i in range(view_class_start, len(lines)):
    if '  @override' in lines[i] and 'Widget build(BuildContext context)' in lines[i+1]:
        build_start = i
        break

# Find helper widget classes start (_Panel, _ModeSegmentedButton, etc.)
helper_widgets_start = None
for i in range(len(lines)-1, 0, -1):
    if 'class _Panel extends StatelessWidget' in lines[i]:
        helper_widgets_start = i
        break

# Create the new view.dart with part directives
new_content = []

# Add imports and part directives
new_content.append("import 'package:flutter/material.dart';\n")
new_content.append("\n")
new_content.append("import '../rust_api.dart';\n")
new_content.append("import 'publish_copy_editor.dart';\n")
new_content.append("import 'publish_schedule_calendar.dart';\n")
new_content.append("\n")
new_content.append("// Part files\n")
new_content.append("part 'view_project_selector.dart';\n")
new_content.append("part 'view_production_panel.dart';\n")
new_content.append("part 'view_candidate_compare.dart';\n")
new_content.append("part 'view_publish_drafts.dart';\n")
new_content.append("part 'view_publish_calendar.dart';\n")
new_content.append("part 'view_publish_jobs.dart';\n")
new_content.append("part 'view_publish_audit.dart';\n")
new_content.append("\n")

# Add all data model classes (from line 7 to view_class_start)
for i in range(7, view_class_start):
    new_content.append(lines[i])

# Add the ShortVideoSpaceView class with simplified build method
new_content.append("class ShortVideoSpaceView extends StatelessWidget {\n")
new_content.append("  const ShortVideoSpaceView({\n")

# Copy constructor parameters
for i in range(view_class_start + 2, build_start):
    new_content.append(lines[i])

# Add simplified build method that uses extracted widgets
new_content.append("  @override\n")
new_content.append("  Widget build(BuildContext context) {\n")
new_content.append("    final theme = Theme.of(context);\n")
new_content.append("    final outline = theme.colorScheme.outline;\n")
new_content.append("    return Column(\n")
new_content.append("      crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("      children: [\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        Text('短视频 Space', style: theme.textTheme.titleLarge),\n")
new_content.append("        const SizedBox(height: 8),\n")
new_content.append("        Text(\n")
new_content.append("          '参考 MoneyPrinterTurbo 的长处，先把\"主题到成片\"的链路聚成一个入口，再逐步把脚本、素材、旁白、字幕和质检串成标准流程。',\n")
new_content.append("          style: theme.textTheme.bodyMedium?.copyWith(color: outline),\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _Panel(\n")
new_content.append("          child: Column(\n")
new_content.append("            crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("            children: [\n")
new_content.append("              Text('创作模式', style: theme.textTheme.titleSmall),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              _ModeSegmentedButton(mode: mode, onChanged: onModeChanged),\n")
new_content.append("              const SizedBox(height: 12),\n")
new_content.append("              Text(modeTitle, style: theme.textTheme.titleMedium),\n")
new_content.append("              const SizedBox(height: 6),\n")
new_content.append("              Text(\n")
new_content.append("                modeSummary,\n")
new_content.append("                style: theme.textTheme.bodyMedium?.copyWith(color: outline),\n")
new_content.append("              ),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              Text(modeAdvice, style: theme.textTheme.bodySmall),\n")
new_content.append("            ],\n")
new_content.append("          ),\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _ProjectSelectorPanel(\n")
new_content.append("          mode: mode,\n")
new_content.append("          onModeChanged: onModeChanged,\n")
new_content.append("          loadingProjects: loadingProjects,\n")
new_content.append("          projectOptions: projectOptions,\n")
new_content.append("          selectedProjectId: selectedProjectId,\n")
new_content.append("          onProjectChanged: onProjectChanged,\n")
new_content.append("          onRefreshProjects: onRefreshProjects,\n")
new_content.append("          videoRatio: videoRatio,\n")
new_content.append("          onVideoRatioChanged: onVideoRatioChanged,\n")
new_content.append("          targetMarket: targetMarket,\n")
new_content.append("          onTargetMarketChanged: onTargetMarketChanged,\n")
new_content.append("          targetPlatforms: targetPlatforms,\n")
new_content.append("          onPublishPlatformTapped: onPublishPlatformTapped,\n")
new_content.append("          durationStrategy: durationStrategy,\n")
new_content.append("          onDurationStrategyChanged: onDurationStrategyChanged,\n")
new_content.append("          voiceProfile: voiceProfile,\n")
new_content.append("          onVoiceProfileChanged: onVoiceProfileChanged,\n")
new_content.append("          subtitleStyle: subtitleStyle,\n")
new_content.append("          onSubtitleStyleChanged: onSubtitleStyleChanged,\n")
new_content.append("          bgmStrategy: bgmStrategy,\n")
new_content.append("          onBgmStrategyChanged: onBgmStrategyChanged,\n")
new_content.append("          creatingProject: creatingProject,\n")
new_content.append("          onCreateProject: onCreateProject,\n")
new_content.append("          savingProjectConfig: savingProjectConfig,\n")
new_content.append("          onSaveProjectConfig: onSaveProjectConfig,\n")
new_content.append("          onOpenProjects: onOpenProjects,\n")
new_content.append("          projectConfigLine: projectConfigLine,\n")
new_content.append("          loadingProjectOverview: loadingProjectOverview,\n")
new_content.append("          projectReadinessSummary: projectReadinessSummary,\n")
new_content.append("          visualLabel: visualLabel,\n")
new_content.append("          directionLabel: directionLabel,\n")
new_content.append("          projectMetrics: projectMetrics,\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _ProductionPanel(\n")
new_content.append("          spaceOverviewSummary: spaceOverviewSummary,\n")
new_content.append("          overviewMetrics: overviewMetrics,\n")
new_content.append("          qualitySummaryLine: qualitySummaryLine,\n")
new_content.append("          badCaseMetrics: badCaseMetrics,\n")
new_content.append("          recentTaskLines: recentTaskLines,\n")
new_content.append("          assetsOverviewPanelUi: assetsOverviewPanelUi,\n")
new_content.append("          assemblyPanelUi: assemblyPanelUi,\n")
new_content.append("          exportCheckPanelUi: exportCheckPanelUi,\n")
new_content.append("          onOpenProductionForAssemblyExport: onOpenProductionForAssemblyExport,\n")
new_content.append("          onOpenAssemblyClipDeskOps: onOpenAssemblyClipDeskOps,\n")
new_content.append("          onOpenAssemblyDefaultsEditor: onOpenAssemblyDefaultsEditor,\n")
new_content.append("        ),\n")
new_content.append("        _CandidateComparePanel(\n")
new_content.append("          candidateCardUi: candidateCardUi,\n")
new_content.append("          candidateComparePanelUi: candidateComparePanelUi,\n")
new_content.append("          onOpenProjectsForCandidateAssets: onOpenProjectsForCandidateAssets,\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _PublishDraftsPanel(publishPanelUi: publishPanelUi),\n")
new_content.append("        _PublishCalendarPanel(publishPanelUi: publishPanelUi),\n")
new_content.append("        _PublishJobsPanel(publishPanelUi: publishPanelUi),\n")
new_content.append("        _PublishAuditPanel(publishPanelUi: publishPanelUi),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _Panel(\n")
new_content.append("          child: Column(\n")
new_content.append("            crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("            children: [\n")
new_content.append("              Text('模式准备度', style: theme.textTheme.titleSmall),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              Text(\n")
new_content.append("                readinessIntro,\n")
new_content.append("                style: theme.textTheme.bodyMedium?.copyWith(color: outline),\n")
new_content.append("              ),\n")
new_content.append("              const SizedBox(height: 12),\n")
new_content.append("              Wrap(\n")
new_content.append("                spacing: 8,\n")
new_content.append("                runSpacing: 8,\n")
new_content.append("                children: [\n")
new_content.append("                  _MetricChip(label: '已就绪', value: readinessCountLabel),\n")
new_content.append("                ],\n")
new_content.append("              ),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              Text(\n")
new_content.append("                readinessGapSummary,\n")
new_content.append("                style: theme.textTheme.bodySmall?.copyWith(color: outline),\n")
new_content.append("              ),\n")
new_content.append("              const SizedBox(height: 12),\n")
new_content.append("              for (final item in readinessItems)\n")
new_content.append("                Padding(\n")
new_content.append("                  padding: const EdgeInsets.only(bottom: 8),\n")
new_content.append("                  child: _ReadinessRow(item: item),\n")
new_content.append("                ),\n")
new_content.append("              const SizedBox(height: 16),\n")
new_content.append("              Text('分镜生成就绪（服务端）', style: theme.textTheme.titleSmall),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              if (shotReadinessUi.loading)\n")
new_content.append("                Text(\n")
new_content.append("                  '正在读取分镜就绪聚合…',\n")
new_content.append("                  style: theme.textTheme.bodySmall?.copyWith(color: outline),\n")
new_content.append("                )\n")
new_content.append("              else if (shotReadinessUi.unavailable)\n")
new_content.append("                Text(\n")
new_content.append("                  '分镜就绪摘要暂不可用，其余概览仍有效。',\n")
new_content.append("                  style: theme.textTheme.bodySmall?.copyWith(color: outline),\n")
new_content.append("                )\n")
new_content.append("              else ...[\ if (shotReadinessUi.headline != null)\n")
new_content.append("                  Text(\n")
new_content.append("                    shotReadinessUi.headline!,\n")
new_content.append("                    style: theme.textTheme.bodyMedium?.copyWith(color: outline),\n")
new_content.append("                  ),\n")
new_content.append("                if (shotReadinessUi.reasonLines.isNotEmpty) ...[\ const SizedBox(height: 8),\n")
new_content.append("                  for (final line in shotReadinessUi.reasonLines)\n")
new_content.append("                    Padding(\n")
new_content.append("                      padding: const EdgeInsets.only(bottom: 4),\n")
new_content.append("                      child: Row(\n")
new_content.append("                        crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("                        children: [\n")
new_content.append("                          Icon(\n")
new_content.append("                            Icons.warning_amber_rounded,\n")
new_content.append("                            size: 16,\n")
new_content.append("                            color: theme.colorScheme.tertiary,\n")
new_content.append("                          ),\n")
new_content.append("                          const SizedBox(width: 6),\n")
new_content.append("                          Expanded(\n")
new_content.append("                            child: Text(\n")
new_content.append("                              line,\n")
new_content.append("                              style: theme.textTheme.bodySmall,\n")
new_content.append("                            ),\n")
new_content.append("                          ),\n")
new_content.append("                        ],\n")
new_content.append("                      ),\n")
new_content.append("                    ),\n")
new_content.append("                ],\n")
new_content.append("                if (shotReadinessUi.shotDetailLines.isNotEmpty) ...[\ const SizedBox(height: 8),\n")
new_content.append("                  Text(\n")
new_content.append("                    '优先处理的分镜',\n")
new_content.append("                    style: theme.textTheme.labelLarge,\n")
new_content.append("                  ),\n")
new_content.append("                  const SizedBox(height: 6),\n")
new_content.append("                  for (final line in shotReadinessUi.shotDetailLines)\n")
new_content.append("                    Padding(\n")
new_content.append("                      padding: const EdgeInsets.only(bottom: 4),\n")
new_content.append("                      child: Row(\n")
new_content.append("                        crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("                        children: [\n")
new_content.append("                          Icon(\n")
new_content.append("                            Icons.movie_filter_outlined,\n")
new_content.append("                            size: 16,\n")
new_content.append("                            color: theme.colorScheme.primary,\n")
new_content.append("                          ),\n")
new_content.append("                          const SizedBox(width: 6),\n")
new_content.append("                          Expanded(\n")
new_content.append("                            child: Text(line, style: theme.textTheme.bodySmall),\n")
new_content.append("                          ),\n")
new_content.append("                        ],\n")
new_content.append("                      ),\n")
new_content.append("                    ),\n")
new_content.append("                ],\n")
new_content.append("                if (onOpenProductionForShotReadiness != null) ...[\ const SizedBox(height: 10),\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenProductionForShotReadiness,\n")
new_content.append("                    icon: const Icon(Icons.movie_creation_outlined),\n")
new_content.append("                    label: const Text('打开制作工作区分镜'),\n")
new_content.append("                  ),\n")
new_content.append("                ],\n")
new_content.append("              ],\n")
new_content.append("            ],\n")
new_content.append("          ),\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _Panel(\n")
new_content.append("          child: Column(\n")
new_content.append("            crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("            children: [\n")
new_content.append("              Text('建议下一步', style: theme.textTheme.titleSmall),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              Text(nextStepTitle, style: theme.textTheme.titleMedium),\n")
new_content.append("              const SizedBox(height: 6),\n")
new_content.append("              Text(\n")
new_content.append("                nextStepDetail,\n")
new_content.append("                style: theme.textTheme.bodyMedium?.copyWith(color: outline),\n")
new_content.append("              ),\n")
new_content.append("              const SizedBox(height: 12),\n")
new_content.append("              FilledButton.icon(\n")
new_content.append("                onPressed: onNextStep,\n")
new_content.append("                icon: const Icon(Icons.arrow_forward_outlined),\n")
new_content.append("                label: Text(nextStepButtonLabel),\n")
new_content.append("              ),\n")
new_content.append("            ],\n")
new_content.append("          ),\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        Wrap(\n")
new_content.append("          spacing: 12,\n")
new_content.append("          runSpacing: 12,\n")
new_content.append("          children: stageCards\n")
new_content.append("              .map(\n")
new_content.append("                (item) => _StageCard(\n")
new_content.append("                  title: item.title,\n")
new_content.append("                  status: item.status,\n")
new_content.append("                  detail: item.detail,\n")
new_content.append("                ),\n")
new_content.append("              )\n")
new_content.append("              .toList(growable: false),\n")
new_content.append("        ),\n")
new_content.append("        const SizedBox(height: 16),\n")
new_content.append("        _Panel(\n")
new_content.append("          child: Column(\n")
new_content.append("            crossAxisAlignment: CrossAxisAlignment.start,\n")
new_content.append("            children: [\n")
new_content.append("              Text('建议迁移顺序', style: theme.textTheme.titleSmall),\n")
new_content.append("              const SizedBox(height: 8),\n")
new_content.append("              Text(migrationSummary, style: theme.textTheme.bodyMedium),\n")
new_content.append("              const SizedBox(height: 12),\n")
new_content.append("              Wrap(\n")
new_content.append("                spacing: 8,\n")
new_content.append("                runSpacing: 8,\n")
new_content.append("                children: [\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenProjects,\n")
new_content.append("                    icon: const Icon(Icons.folder_open_outlined),\n")
new_content.append("                    label: const Text('项目'),\n")
new_content.append("                  ),\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenScriptWorkspace,\n")
new_content.append("                    icon: const Icon(Icons.edit_note_outlined),\n")
new_content.append("                    label: const Text('脚本工作区'),\n")
new_content.append("                  ),\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenProductionWorkspace,\n")
new_content.append("                    icon: const Icon(Icons.movie_creation_outlined),\n")
new_content.append("                    label: const Text('制作工作区'),\n")
new_content.append("                  ),\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenTasks,\n")
new_content.append("                    icon: const Icon(Icons.checklist_outlined),\n")
new_content.append("                    label: const Text('任务中心'),\n")
new_content.append("                  ),\n")
new_content.append("                  OutlinedButton.icon(\n")
new_content.append("                    onPressed: onOpenQuality,\n")
new_content.append("                    icon: const Icon(Icons.fact_check_outlined),\n")
new_content.append("                    label: const Text('质量评审'),\n")
new_content.append("                  ),\n")
new_content.append("                ],\n")
new_content.append("              ),\n")
new_content.append("            ],\n")
new_content.append("          ),\n")
new_content.append("        ),\n")
new_content.append("      ],\n")
new_content.append("    );\n")
new_content.append("  }\n")
new_content.append("}\n")
new_content.append("\n")

# Add helper widgets from the original file
for i in range(helper_widgets_start, len(lines)):
    new_content.append(lines[i])

# Write the new file
with open('frontend/lib/short_video_space/view.dart', 'w', encoding='utf-8') as f:
    f.writelines(new_content)

print(f"Refactored view.dart created successfully!")
print(f"Original file: {len(lines)} lines")
print(f"New file: {len(new_content)} lines")
