//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct VersionResponse;
impl PartialSchema for VersionResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VersionResponse")
    }
}
impl ToSchema for VersionResponse {}

pub struct VideoItem;
impl PartialSchema for VideoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VideoItem")
    }
}
impl ToSchema for VideoItem {}

pub struct VisualManualEntry;
impl PartialSchema for VisualManualEntry {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VisualManualEntry")
    }
}
impl ToSchema for VisualManualEntry {}

pub struct VisualManualResponse;
impl PartialSchema for VisualManualResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VisualManualResponse")
    }
}
impl ToSchema for VisualManualResponse {}

pub struct VisualManualStyle;
impl PartialSchema for VisualManualStyle {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VisualManualStyle")
    }
}
impl ToSchema for VisualManualStyle {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<VersionResponse>();
    c = c.schema_from::<VideoItem>();
    c = c.schema_from::<VisualManualEntry>();
    c = c.schema_from::<VisualManualResponse>();
    c = c.schema_from::<VisualManualStyle>();
    c
}
