//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct LegacyDirectorManualDeleteBody;
impl PartialSchema for LegacyDirectorManualDeleteBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualDeleteBody")
    }
}
impl ToSchema for LegacyDirectorManualDeleteBody {}

pub struct LegacyDirectorManualDeleteResponse;
impl PartialSchema for LegacyDirectorManualDeleteResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualDeleteResponse")
    }
}
impl ToSchema for LegacyDirectorManualDeleteResponse {}

pub struct LegacyDirectorManualEditBody;
impl PartialSchema for LegacyDirectorManualEditBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualEditBody")
    }
}
impl ToSchema for LegacyDirectorManualEditBody {}

pub struct LegacyDirectorManualListResponse;
impl PartialSchema for LegacyDirectorManualListResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualListResponse")
    }
}
impl ToSchema for LegacyDirectorManualListResponse {}

pub struct LegacyDirectorManualSlotRow;
impl PartialSchema for LegacyDirectorManualSlotRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualSlotRow")
    }
}
impl ToSchema for LegacyDirectorManualSlotRow {}

pub struct LegacyDirectorManualStyleRow;
impl PartialSchema for LegacyDirectorManualStyleRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualStyleRow")
    }
}
impl ToSchema for LegacyDirectorManualStyleRow {}

pub struct LegacyEmptyObjectResponse;
impl PartialSchema for LegacyEmptyObjectResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyEmptyObjectResponse")
    }
}
impl ToSchema for LegacyEmptyObjectResponse {}

pub struct LegacyGenerateNovelEventsBody;
impl PartialSchema for LegacyGenerateNovelEventsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyGenerateNovelEventsBody")
    }
}
impl ToSchema for LegacyGenerateNovelEventsBody {}

pub struct LegacyGetEventsBody;
impl PartialSchema for LegacyGetEventsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyGetEventsBody")
    }
}
impl ToSchema for LegacyGetEventsBody {}

pub struct LegacyNovelAddNovelBody;
impl PartialSchema for LegacyNovelAddNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelAddNovelBody")
    }
}
impl ToSchema for LegacyNovelAddNovelBody {}

pub struct LegacyNovelAddNovelItem;
impl PartialSchema for LegacyNovelAddNovelItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelAddNovelItem")
    }
}
impl ToSchema for LegacyNovelAddNovelItem {}

pub struct LegacyNovelBatchDeleteBody;
impl PartialSchema for LegacyNovelBatchDeleteBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelBatchDeleteBody")
    }
}
impl ToSchema for LegacyNovelBatchDeleteBody {}

pub struct LegacyNovelDataResponse;
impl PartialSchema for LegacyNovelDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelDataResponse")
    }
}
impl ToSchema for LegacyNovelDataResponse {}

pub struct LegacyNovelDeleteNovelBody;
impl PartialSchema for LegacyNovelDeleteNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelDeleteNovelBody")
    }
}
impl ToSchema for LegacyNovelDeleteNovelBody {}

pub struct LegacyNovelEventListResponse;
impl PartialSchema for LegacyNovelEventListResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventListResponse")
    }
}
impl ToSchema for LegacyNovelEventListResponse {}

pub struct LegacyNovelEventRow;
impl PartialSchema for LegacyNovelEventRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventRow")
    }
}
impl ToSchema for LegacyNovelEventRow {}

pub struct LegacyNovelEventStateItem;
impl PartialSchema for LegacyNovelEventStateItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventStateItem")
    }
}
impl ToSchema for LegacyNovelEventStateItem {}

pub struct LegacyNovelEventStateResponse;
impl PartialSchema for LegacyNovelEventStateResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventStateResponse")
    }
}
impl ToSchema for LegacyNovelEventStateResponse {}

pub struct LegacyNovelGetNovelBody;
impl PartialSchema for LegacyNovelGetNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelGetNovelBody")
    }
}
impl ToSchema for LegacyNovelGetNovelBody {}

pub struct LegacyNovelGetNovelEventStateBody;
impl PartialSchema for LegacyNovelGetNovelEventStateBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelGetNovelEventStateBody")
    }
}
impl ToSchema for LegacyNovelGetNovelEventStateBody {}

pub struct LegacyNovelGetNovelPageRow;
impl PartialSchema for LegacyNovelGetNovelPageRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelGetNovelPageRow")
    }
}
impl ToSchema for LegacyNovelGetNovelPageRow {}

pub struct LegacyNovelGetNovelResponse;
impl PartialSchema for LegacyNovelGetNovelResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelGetNovelResponse")
    }
}
impl ToSchema for LegacyNovelGetNovelResponse {}

pub struct LegacyNovelIndexItem;
impl PartialSchema for LegacyNovelIndexItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelIndexItem")
    }
}
impl ToSchema for LegacyNovelIndexItem {}

pub struct LegacyNovelIndexResponse;
impl PartialSchema for LegacyNovelIndexResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelIndexResponse")
    }
}
impl ToSchema for LegacyNovelIndexResponse {}

pub struct LegacyNovelOkMessageResponse;
impl PartialSchema for LegacyNovelOkMessageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelOkMessageResponse")
    }
}
impl ToSchema for LegacyNovelOkMessageResponse {}

pub struct LegacyNovelProjectIdBody;
impl PartialSchema for LegacyNovelProjectIdBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelProjectIdBody")
    }
}
impl ToSchema for LegacyNovelProjectIdBody {}

pub struct LegacyNovelUpdateNovelBody;
impl PartialSchema for LegacyNovelUpdateNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelUpdateNovelBody")
    }
}
impl ToSchema for LegacyNovelUpdateNovelBody {}

pub struct LegacyProjectAddProjectBody;
impl PartialSchema for LegacyProjectAddProjectBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyProjectAddProjectBody")
    }
}
impl ToSchema for LegacyProjectAddProjectBody {}

pub struct LegacyProjectDeleteProjectBody;
impl PartialSchema for LegacyProjectDeleteProjectBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyProjectDeleteProjectBody")
    }
}
impl ToSchema for LegacyProjectDeleteProjectBody {}

pub struct LegacyProjectDeleteProjectResponse;
impl PartialSchema for LegacyProjectDeleteProjectResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyProjectDeleteProjectResponse")
    }
}
impl ToSchema for LegacyProjectDeleteProjectResponse {}

pub struct LegacyProjectEditProjectBody;
impl PartialSchema for LegacyProjectEditProjectBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyProjectEditProjectBody")
    }
}
impl ToSchema for LegacyProjectEditProjectBody {}

pub struct LegacyProjectMutationMessageResponse;
impl PartialSchema for LegacyProjectMutationMessageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyProjectMutationMessageResponse")
    }
}
impl ToSchema for LegacyProjectMutationMessageResponse {}

pub struct LegacyScriptRelatedAssetBrief;
impl PartialSchema for LegacyScriptRelatedAssetBrief {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyScriptRelatedAssetBrief")
    }
}
impl ToSchema for LegacyScriptRelatedAssetBrief {}

pub struct LegacyScriptsGetScriptApiItem;
impl PartialSchema for LegacyScriptsGetScriptApiItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyScriptsGetScriptApiItem")
    }
}
impl ToSchema for LegacyScriptsGetScriptApiItem {}

pub struct LegacyScriptsGetScriptApiResponse;
impl PartialSchema for LegacyScriptsGetScriptApiResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyScriptsGetScriptApiResponse")
    }
}
impl ToSchema for LegacyScriptsGetScriptApiResponse {}

pub struct LegacyTasksEmptyBody;
impl PartialSchema for LegacyTasksEmptyBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyTasksEmptyBody")
    }
}
impl ToSchema for LegacyTasksEmptyBody {}

pub struct LegacyVisualManualAddBody;
impl PartialSchema for LegacyVisualManualAddBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyVisualManualAddBody")
    }
}
impl ToSchema for LegacyVisualManualAddBody {}

pub struct LegacyVisualManualEditBody;
impl PartialSchema for LegacyVisualManualEditBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyVisualManualEditBody")
    }
}
impl ToSchema for LegacyVisualManualEditBody {}

pub struct ListArtStylesResponse;
impl PartialSchema for ListArtStylesResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ListArtStylesResponse")
    }
}
impl ToSchema for ListArtStylesResponse {}

pub struct ListAssetImagesResponse;
impl PartialSchema for ListAssetImagesResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ListAssetImagesResponse")
    }
}
impl ToSchema for ListAssetImagesResponse {}

pub struct ListAssetsResponse;
impl PartialSchema for ListAssetsResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ListAssetsResponse")
    }
}
impl ToSchema for ListAssetsResponse {}

pub struct ListNovelsResponse;
impl PartialSchema for ListNovelsResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ListNovelsResponse")
    }
}
impl ToSchema for ListNovelsResponse {}

pub struct MeResponse;
impl PartialSchema for MeResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MeResponse")
    }
}
impl ToSchema for MeResponse {}

pub struct MemoryConfig;
impl PartialSchema for MemoryConfig {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MemoryConfig")
    }
}
impl ToSchema for MemoryConfig {}

pub struct MemoryConfigSavedResponse;
impl PartialSchema for MemoryConfigSavedResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MemoryConfigSavedResponse")
    }
}
impl ToSchema for MemoryConfigSavedResponse {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<LegacyDirectorManualDeleteBody>();
    c = c.schema_from::<LegacyDirectorManualDeleteResponse>();
    c = c.schema_from::<LegacyDirectorManualEditBody>();
    c = c.schema_from::<LegacyDirectorManualListResponse>();
    c = c.schema_from::<LegacyDirectorManualSlotRow>();
    c = c.schema_from::<LegacyDirectorManualStyleRow>();
    c = c.schema_from::<LegacyEmptyObjectResponse>();
    c = c.schema_from::<LegacyGenerateNovelEventsBody>();
    c = c.schema_from::<LegacyGetEventsBody>();
    c = c.schema_from::<LegacyNovelAddNovelBody>();
    c = c.schema_from::<LegacyNovelAddNovelItem>();
    c = c.schema_from::<LegacyNovelBatchDeleteBody>();
    c = c.schema_from::<LegacyNovelDataResponse>();
    c = c.schema_from::<LegacyNovelDeleteNovelBody>();
    c = c.schema_from::<LegacyNovelEventListResponse>();
    c = c.schema_from::<LegacyNovelEventRow>();
    c = c.schema_from::<LegacyNovelEventStateItem>();
    c = c.schema_from::<LegacyNovelEventStateResponse>();
    c = c.schema_from::<LegacyNovelGetNovelBody>();
    c = c.schema_from::<LegacyNovelGetNovelEventStateBody>();
    c = c.schema_from::<LegacyNovelGetNovelPageRow>();
    c = c.schema_from::<LegacyNovelGetNovelResponse>();
    c = c.schema_from::<LegacyNovelIndexItem>();
    c = c.schema_from::<LegacyNovelIndexResponse>();
    c = c.schema_from::<LegacyNovelOkMessageResponse>();
    c = c.schema_from::<LegacyNovelProjectIdBody>();
    c = c.schema_from::<LegacyNovelUpdateNovelBody>();
    c = c.schema_from::<LegacyProjectAddProjectBody>();
    c = c.schema_from::<LegacyProjectDeleteProjectBody>();
    c = c.schema_from::<LegacyProjectDeleteProjectResponse>();
    c = c.schema_from::<LegacyProjectEditProjectBody>();
    c = c.schema_from::<LegacyProjectMutationMessageResponse>();
    c = c.schema_from::<LegacyScriptRelatedAssetBrief>();
    c = c.schema_from::<LegacyScriptsGetScriptApiItem>();
    c = c.schema_from::<LegacyScriptsGetScriptApiResponse>();
    c = c.schema_from::<LegacyTasksEmptyBody>();
    c = c.schema_from::<LegacyVisualManualAddBody>();
    c = c.schema_from::<LegacyVisualManualEditBody>();
    c = c.schema_from::<ListArtStylesResponse>();
    c = c.schema_from::<ListAssetImagesResponse>();
    c = c.schema_from::<ListAssetsResponse>();
    c = c.schema_from::<ListNovelsResponse>();
    c = c.schema_from::<MeResponse>();
    c = c.schema_from::<MemoryConfig>();
    c = c.schema_from::<MemoryConfigSavedResponse>();
    c
}
