//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct AboutCheckUpdateRequest;
impl PartialSchema for AboutCheckUpdateRequest {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AboutCheckUpdateRequest")
    }
}
impl ToSchema for AboutCheckUpdateRequest {}

pub struct AboutCheckUpdateResponse;
impl PartialSchema for AboutCheckUpdateResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AboutCheckUpdateResponse")
    }
}
impl ToSchema for AboutCheckUpdateResponse {}

pub struct AboutCheckUpdateSource;
impl PartialSchema for AboutCheckUpdateSource {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AboutCheckUpdateSource")
    }
}
impl ToSchema for AboutCheckUpdateSource {}

pub struct AboutDownloadAppRequest;
impl PartialSchema for AboutDownloadAppRequest {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AboutDownloadAppRequest")
    }
}
impl ToSchema for AboutDownloadAppRequest {}

pub struct AgentDeployKeyIgnoredResponse;
impl PartialSchema for AgentDeployKeyIgnoredResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AgentDeployKeyIgnoredResponse")
    }
}
impl ToSchema for AgentDeployKeyIgnoredResponse {}

pub struct AgentDeployListBody;
impl PartialSchema for AgentDeployListBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AgentDeployListBody")
    }
}
impl ToSchema for AgentDeployListBody {}

pub struct AgentDeployListItem;
impl PartialSchema for AgentDeployListItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AgentDeployListItem")
    }
}
impl ToSchema for AgentDeployListItem {}

pub struct AgentDeploySavedResponse;
impl PartialSchema for AgentDeploySavedResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AgentDeploySavedResponse")
    }
}
impl ToSchema for AgentDeploySavedResponse {}

pub struct AgentSetKeyBody;
impl PartialSchema for AgentSetKeyBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AgentSetKeyBody")
    }
}
impl ToSchema for AgentSetKeyBody {}

pub struct AppendAgentMemoryBody;
impl PartialSchema for AppendAgentMemoryBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AppendAgentMemoryBody")
    }
}
impl ToSchema for AppendAgentMemoryBody {}

pub struct AppendAgentMemoryResponse;
impl PartialSchema for AppendAgentMemoryResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AppendAgentMemoryResponse")
    }
}
impl ToSchema for AppendAgentMemoryResponse {}

pub struct ArtStyleRow;
impl PartialSchema for ArtStyleRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ArtStyleRow")
    }
}
impl ToSchema for ArtStyleRow {}

pub struct AssetGenTypeV1;
impl PartialSchema for AssetGenTypeV1 {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetGenTypeV1")
    }
}
impl ToSchema for AssetGenTypeV1 {}

pub struct AssetImageListItem;
impl PartialSchema for AssetImageListItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetImageListItem")
    }
}
impl ToSchema for AssetImageListItem {}

pub struct AssetImageRow;
impl PartialSchema for AssetImageRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetImageRow")
    }
}
impl ToSchema for AssetImageRow {}

pub struct AssetRow;
impl PartialSchema for AssetRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetRow")
    }
}
impl ToSchema for AssetRow {}

pub struct AssetsGenerateCancelBody;
impl PartialSchema for AssetsGenerateCancelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetsGenerateCancelBody")
    }
}
impl ToSchema for AssetsGenerateCancelBody {}

pub struct BatchAddScriptDataBody;
impl PartialSchema for BatchAddScriptDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchAddScriptDataBody")
    }
}
impl ToSchema for BatchAddScriptDataBody {}

pub struct BatchAddScriptItem;
impl PartialSchema for BatchAddScriptItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchAddScriptItem")
    }
}
impl ToSchema for BatchAddScriptItem {}

pub struct BatchAddScriptResponse;
impl PartialSchema for BatchAddScriptResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchAddScriptResponse")
    }
}
impl ToSchema for BatchAddScriptResponse {}

pub struct BatchDeleteNovelEventsBody;
impl PartialSchema for BatchDeleteNovelEventsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchDeleteNovelEventsBody")
    }
}
impl ToSchema for BatchDeleteNovelEventsBody {}

pub struct BatchGenerateImageAssetsBody;
impl PartialSchema for BatchGenerateImageAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchGenerateImageAssetsBody")
    }
}
impl ToSchema for BatchGenerateImageAssetsBody {}

pub struct BatchGenerateImageItem;
impl PartialSchema for BatchGenerateImageItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchGenerateImageItem")
    }
}
impl ToSchema for BatchGenerateImageItem {}

pub struct BatchPolishAssetsItem;
impl PartialSchema for BatchPolishAssetsItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchPolishAssetsItem")
    }
}
impl ToSchema for BatchPolishAssetsItem {}

pub struct BatchPolishAssetsPromptBody;
impl PartialSchema for BatchPolishAssetsPromptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchPolishAssetsPromptBody")
    }
}
impl ToSchema for BatchPolishAssetsPromptBody {}

pub struct BillingWebhookEventItem;
impl PartialSchema for BillingWebhookEventItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BillingWebhookEventItem")
    }
}
impl ToSchema for BillingWebhookEventItem {}

pub struct BillingWebhookEventsResponse;
impl PartialSchema for BillingWebhookEventsResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BillingWebhookEventsResponse")
    }
}
impl ToSchema for BillingWebhookEventsResponse {}

pub struct BillingWebhookResponse;
impl PartialSchema for BillingWebhookResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BillingWebhookResponse")
    }
}
impl ToSchema for BillingWebhookResponse {}

pub struct ClearAgentMemoryBody;
impl PartialSchema for ClearAgentMemoryBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ClearAgentMemoryBody")
    }
}
impl ToSchema for ClearAgentMemoryBody {}

pub struct ClearAgentMemoryResponse;
impl PartialSchema for ClearAgentMemoryResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ClearAgentMemoryResponse")
    }
}
impl ToSchema for ClearAgentMemoryResponse {}

pub struct CornerScapeAssetItem;
impl PartialSchema for CornerScapeAssetItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeAssetItem")
    }
}
impl ToSchema for CornerScapeAssetItem {}

pub struct CornerScapeHistoryImage;
impl PartialSchema for CornerScapeHistoryImage {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeHistoryImage")
    }
}
impl ToSchema for CornerScapeHistoryImage {}

pub struct CornerScapeRequestBody;
impl PartialSchema for CornerScapeRequestBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeRequestBody")
    }
}
impl ToSchema for CornerScapeRequestBody {}

pub struct CornerScapeResponse;
impl PartialSchema for CornerScapeResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeResponse")
    }
}
impl ToSchema for CornerScapeResponse {}

pub struct CreateArtStyleBody;
impl PartialSchema for CreateArtStyleBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateArtStyleBody")
    }
}
impl ToSchema for CreateArtStyleBody {}

pub struct CreateAssetBody;
impl PartialSchema for CreateAssetBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateAssetBody")
    }
}
impl ToSchema for CreateAssetBody {}

pub struct CreateAssetImageBody;
impl PartialSchema for CreateAssetImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateAssetImageBody")
    }
}
impl ToSchema for CreateAssetImageBody {}

pub struct CreateJobBody;
impl PartialSchema for CreateJobBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateJobBody")
    }
}
impl ToSchema for CreateJobBody {}

pub struct CreateNovelBody;
impl PartialSchema for CreateNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateNovelBody")
    }
}
impl ToSchema for CreateNovelBody {}

pub struct CreateNovelEventBody;
impl PartialSchema for CreateNovelEventBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateNovelEventBody")
    }
}
impl ToSchema for CreateNovelEventBody {}

pub struct CreateProjectBody;
impl PartialSchema for CreateProjectBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateProjectBody")
    }
}
impl ToSchema for CreateProjectBody {}

pub struct CreateQualityReviewBody;
impl PartialSchema for CreateQualityReviewBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateQualityReviewBody")
    }
}
impl ToSchema for CreateQualityReviewBody {}

pub struct CreateScriptBody;
impl PartialSchema for CreateScriptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateScriptBody")
    }
}
impl ToSchema for CreateScriptBody {}

pub struct CreateStoryboardBody;
impl PartialSchema for CreateStoryboardBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CreateStoryboardBody")
    }
}
impl ToSchema for CreateStoryboardBody {}

pub struct DeployAgentModelBody;
impl PartialSchema for DeployAgentModelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("DeployAgentModelBody")
    }
}
impl ToSchema for DeployAgentModelBody {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<AboutCheckUpdateRequest>();
    c = c.schema_from::<AboutCheckUpdateResponse>();
    c = c.schema_from::<AboutCheckUpdateSource>();
    c = c.schema_from::<AboutDownloadAppRequest>();
    c = c.schema_from::<AgentDeployKeyIgnoredResponse>();
    c = c.schema_from::<AgentDeployListBody>();
    c = c.schema_from::<AgentDeployListItem>();
    c = c.schema_from::<AgentDeploySavedResponse>();
    c = c.schema_from::<AgentSetKeyBody>();
    c = c.schema_from::<AppendAgentMemoryBody>();
    c = c.schema_from::<AppendAgentMemoryResponse>();
    c = c.schema_from::<ArtStyleRow>();
    c = c.schema_from::<AssetGenTypeV1>();
    c = c.schema_from::<AssetImageListItem>();
    c = c.schema_from::<AssetImageRow>();
    c = c.schema_from::<AssetRow>();
    c = c.schema_from::<AssetsGenerateCancelBody>();
    c = c.schema_from::<BatchAddScriptDataBody>();
    c = c.schema_from::<BatchAddScriptItem>();
    c = c.schema_from::<BatchAddScriptResponse>();
    c = c.schema_from::<BatchDeleteNovelEventsBody>();
    c = c.schema_from::<BatchGenerateImageAssetsBody>();
    c = c.schema_from::<BatchGenerateImageItem>();
    c = c.schema_from::<BatchPolishAssetsItem>();
    c = c.schema_from::<BatchPolishAssetsPromptBody>();
    c = c.schema_from::<BillingWebhookEventItem>();
    c = c.schema_from::<BillingWebhookEventsResponse>();
    c = c.schema_from::<BillingWebhookResponse>();
    c = c.schema_from::<ClearAgentMemoryBody>();
    c = c.schema_from::<ClearAgentMemoryResponse>();
    c = c.schema_from::<CornerScapeAssetItem>();
    c = c.schema_from::<CornerScapeHistoryImage>();
    c = c.schema_from::<CornerScapeRequestBody>();
    c = c.schema_from::<CornerScapeResponse>();
    c = c.schema_from::<CreateArtStyleBody>();
    c = c.schema_from::<CreateAssetBody>();
    c = c.schema_from::<CreateAssetImageBody>();
    c = c.schema_from::<CreateJobBody>();
    c = c.schema_from::<CreateNovelBody>();
    c = c.schema_from::<CreateNovelEventBody>();
    c = c.schema_from::<CreateProjectBody>();
    c = c.schema_from::<CreateQualityReviewBody>();
    c = c.schema_from::<CreateScriptBody>();
    c = c.schema_from::<CreateStoryboardBody>();
    c = c.schema_from::<DeployAgentModelBody>();
    c
}
