//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct ScriptRow;
impl PartialSchema for ScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptRow")
    }
}
impl ToSchema for ScriptRow {}

pub struct SetScriptAgentPlanData;
impl PartialSchema for SetScriptAgentPlanData {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SetScriptAgentPlanData")
    }
}
impl ToSchema for SetScriptAgentPlanData {}

pub struct SetScriptAgentPlanScriptRow;
impl PartialSchema for SetScriptAgentPlanScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SetScriptAgentPlanScriptRow")
    }
}
impl ToSchema for SetScriptAgentPlanScriptRow {}

pub struct UpdateScriptAgentDataPayload;
impl PartialSchema for UpdateScriptAgentDataPayload {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateScriptAgentDataPayload")
    }
}
impl ToSchema for UpdateScriptAgentDataPayload {}

pub struct UpdateScriptAgentScriptRow;
impl PartialSchema for UpdateScriptAgentScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateScriptAgentScriptRow")
    }
}
impl ToSchema for UpdateScriptAgentScriptRow {}

pub struct VendorConfigEntry;
impl PartialSchema for VendorConfigEntry {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorConfigEntry")
    }
}
impl ToSchema for VendorConfigEntry {}

pub struct VendorMutationResponse;
impl PartialSchema for VendorMutationResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorMutationResponse")
    }
}
impl ToSchema for VendorMutationResponse {}

pub struct VendorSummaryItem;
impl PartialSchema for VendorSummaryItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorSummaryItem")
    }
}
impl ToSchema for VendorSummaryItem {}

pub struct VideoItem;
impl PartialSchema for VideoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VideoItem")
    }
}
impl ToSchema for VideoItem {}

pub struct VisualManualEntry;
impl PartialSchema for VisualManualEntry {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VisualManualEntry")
    }
}
impl ToSchema for VisualManualEntry {}

pub struct VisualManualStyle;
impl PartialSchema for VisualManualStyle {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VisualManualStyle")
    }
}
impl ToSchema for VisualManualStyle {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<ScriptRow>();
    c = c.schema_from::<SetScriptAgentPlanData>();
    c = c.schema_from::<SetScriptAgentPlanScriptRow>();
    c = c.schema_from::<UpdateScriptAgentDataPayload>();
    c = c.schema_from::<UpdateScriptAgentScriptRow>();
    c = c.schema_from::<VendorConfigEntry>();
    c = c.schema_from::<VendorMutationResponse>();
    c = c.schema_from::<VendorSummaryItem>();
    c = c.schema_from::<VideoItem>();
    c = c.schema_from::<VisualManualEntry>();
    c = c.schema_from::<VisualManualStyle>();
    c
}
