//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct DownloadAppAcceptedResponse;
impl PartialSchema for DownloadAppAcceptedResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("DownloadAppAcceptedResponse")
    }
}
impl ToSchema for DownloadAppAcceptedResponse {}

pub struct ErrorBody;
impl PartialSchema for ErrorBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ErrorBody")
    }
}
impl ToSchema for ErrorBody {}

pub struct ExportScriptsBody;
impl PartialSchema for ExportScriptsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ExportScriptsBody")
    }
}
impl ToSchema for ExportScriptsBody {}

pub struct ExtractArtStylePromptBody;
impl PartialSchema for ExtractArtStylePromptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ExtractArtStylePromptBody")
    }
}
impl ToSchema for ExtractArtStylePromptBody {}

pub struct ExtractArtStylePromptResponse;
impl PartialSchema for ExtractArtStylePromptResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ExtractArtStylePromptResponse")
    }
}
impl ToSchema for ExtractArtStylePromptResponse {}

pub struct ExtractAssetsAcceptedResponse;
impl PartialSchema for ExtractAssetsAcceptedResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ExtractAssetsAcceptedResponse")
    }
}
impl ToSchema for ExtractAssetsAcceptedResponse {}

pub struct ExtractAssetsStartBody;
impl PartialSchema for ExtractAssetsStartBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ExtractAssetsStartBody")
    }
}
impl ToSchema for ExtractAssetsStartBody {}

pub struct GenerateAssetsBody;
impl PartialSchema for GenerateAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("GenerateAssetsBody")
    }
}
impl ToSchema for GenerateAssetsBody {}

pub struct GenerateNovelEventsBody;
impl PartialSchema for GenerateNovelEventsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("GenerateNovelEventsBody")
    }
}
impl ToSchema for GenerateNovelEventsBody {}

pub struct GetScriptAgentPlanBody;
impl PartialSchema for GetScriptAgentPlanBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("GetScriptAgentPlanBody")
    }
}
impl ToSchema for GetScriptAgentPlanBody {}

pub struct HarnessToolInfo;
impl PartialSchema for HarnessToolInfo {
    fn schema() -> RefOr<Schema> {
        legacy_pick("HarnessToolInfo")
    }
}
impl ToSchema for HarnessToolInfo {}

pub struct HarnessToolsResponse;
impl PartialSchema for HarnessToolsResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("HarnessToolsResponse")
    }
}
impl ToSchema for HarnessToolsResponse {}

pub struct HealthResponse;
impl PartialSchema for HealthResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("HealthResponse")
    }
}
impl ToSchema for HealthResponse {}

pub struct JobKindSummary;
impl PartialSchema for JobKindSummary {
    fn schema() -> RefOr<Schema> {
        legacy_pick("JobKindSummary")
    }
}
impl ToSchema for JobKindSummary {}

pub struct JobRow;
impl PartialSchema for JobRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("JobRow")
    }
}
impl ToSchema for JobRow {}

pub struct JobStatusSummary;
impl PartialSchema for JobStatusSummary {
    fn schema() -> RefOr<Schema> {
        legacy_pick("JobStatusSummary")
    }
}
impl ToSchema for JobStatusSummary {}

pub struct JobsPageResponse;
impl PartialSchema for JobsPageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("JobsPageResponse")
    }
}
impl ToSchema for JobsPageResponse {}

pub struct LegacyAssetsAddAssetsBody;
impl PartialSchema for LegacyAssetsAddAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsAddAssetsBody")
    }
}
impl ToSchema for LegacyAssetsAddAssetsBody {}

pub struct LegacyAssetsBatchDeleteBody;
impl PartialSchema for LegacyAssetsBatchDeleteBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsBatchDeleteBody")
    }
}
impl ToSchema for LegacyAssetsBatchDeleteBody {}

pub struct LegacyAssetsBatchGenerationDataBody;
impl PartialSchema for LegacyAssetsBatchGenerationDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsBatchGenerationDataBody")
    }
}
impl ToSchema for LegacyAssetsBatchGenerationDataBody {}

pub struct LegacyAssetsBatchGenerationDataItem;
impl PartialSchema for LegacyAssetsBatchGenerationDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsBatchGenerationDataItem")
    }
}
impl ToSchema for LegacyAssetsBatchGenerationDataItem {}

pub struct LegacyAssetsBatchGenerationDataResponse;
impl PartialSchema for LegacyAssetsBatchGenerationDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsBatchGenerationDataResponse")
    }
}
impl ToSchema for LegacyAssetsBatchGenerationDataResponse {}

pub struct LegacyAssetsDeleteBody;
impl PartialSchema for LegacyAssetsDeleteBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsDeleteBody")
    }
}
impl ToSchema for LegacyAssetsDeleteBody {}

pub struct LegacyAssetsGetAssetsApiBody;
impl PartialSchema for LegacyAssetsGetAssetsApiBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiBody")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiBody {}

pub struct LegacyAssetsGetAssetsApiChildItem;
impl PartialSchema for LegacyAssetsGetAssetsApiChildItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiChildItem")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiChildItem {}

pub struct LegacyAssetsGetAssetsApiParentItem;
impl PartialSchema for LegacyAssetsGetAssetsApiParentItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiParentItem")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiParentItem {}

pub struct LegacyAssetsGetAssetsApiResponse;
impl PartialSchema for LegacyAssetsGetAssetsApiResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiResponse")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiResponse {}

pub struct LegacyAssetsGetImageBody;
impl PartialSchema for LegacyAssetsGetImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetImageBody")
    }
}
impl ToSchema for LegacyAssetsGetImageBody {}

pub struct LegacyAssetsGetImageResponse;
impl PartialSchema for LegacyAssetsGetImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetImageResponse")
    }
}
impl ToSchema for LegacyAssetsGetImageResponse {}

pub struct LegacyAssetsGetImageTempAsset;
impl PartialSchema for LegacyAssetsGetImageTempAsset {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetImageTempAsset")
    }
}
impl ToSchema for LegacyAssetsGetImageTempAsset {}

pub struct LegacyAssetsGetMaterialDataBody;
impl PartialSchema for LegacyAssetsGetMaterialDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataBody")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataBody {}

pub struct LegacyAssetsGetMaterialDataItem;
impl PartialSchema for LegacyAssetsGetMaterialDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataItem")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataItem {}

pub struct LegacyAssetsGetMaterialDataResponse;
impl PartialSchema for LegacyAssetsGetMaterialDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataResponse")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataResponse {}

pub struct LegacyAssetsGetMaterialDataVideoItem;
impl PartialSchema for LegacyAssetsGetMaterialDataVideoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataVideoItem")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataVideoItem {}

pub struct LegacyAssetsMutationResponse;
impl PartialSchema for LegacyAssetsMutationResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsMutationResponse")
    }
}
impl ToSchema for LegacyAssetsMutationResponse {}

pub struct LegacyAssetsPollingImageAssetsBody;
impl PartialSchema for LegacyAssetsPollingImageAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsPollingImageAssetsBody")
    }
}
impl ToSchema for LegacyAssetsPollingImageAssetsBody {}

pub struct LegacyAssetsPollingImageAssetsItem;
impl PartialSchema for LegacyAssetsPollingImageAssetsItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsPollingImageAssetsItem")
    }
}
impl ToSchema for LegacyAssetsPollingImageAssetsItem {}

pub struct LegacyAssetsPollingPromptAssetsBody;
impl PartialSchema for LegacyAssetsPollingPromptAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsPollingPromptAssetsBody")
    }
}
impl ToSchema for LegacyAssetsPollingPromptAssetsBody {}

pub struct LegacyAssetsPollingPromptAssetsItem;
impl PartialSchema for LegacyAssetsPollingPromptAssetsItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsPollingPromptAssetsItem")
    }
}
impl ToSchema for LegacyAssetsPollingPromptAssetsItem {}

pub struct LegacyAssetsSaveAssetsBody;
impl PartialSchema for LegacyAssetsSaveAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsSaveAssetsBody")
    }
}
impl ToSchema for LegacyAssetsSaveAssetsBody {}

pub struct LegacyAssetsUpdateAssetsBody;
impl PartialSchema for LegacyAssetsUpdateAssetsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsUpdateAssetsBody")
    }
}
impl ToSchema for LegacyAssetsUpdateAssetsBody {}

pub struct LegacyAssetsUploadClipBody;
impl PartialSchema for LegacyAssetsUploadClipBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsUploadClipBody")
    }
}
impl ToSchema for LegacyAssetsUploadClipBody {}

pub struct LegacyAssetsUploadClipResponse;
impl PartialSchema for LegacyAssetsUploadClipResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsUploadClipResponse")
    }
}
impl ToSchema for LegacyAssetsUploadClipResponse {}

pub struct LegacyDirectorManualAddBody;
impl PartialSchema for LegacyDirectorManualAddBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualAddBody")
    }
}
impl ToSchema for LegacyDirectorManualAddBody {}

pub struct LegacyDirectorManualDataSlot;
impl PartialSchema for LegacyDirectorManualDataSlot {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualDataSlot")
    }
}
impl ToSchema for LegacyDirectorManualDataSlot {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<DownloadAppAcceptedResponse>();
    c = c.schema_from::<ErrorBody>();
    c = c.schema_from::<ExportScriptsBody>();
    c = c.schema_from::<ExtractArtStylePromptBody>();
    c = c.schema_from::<ExtractArtStylePromptResponse>();
    c = c.schema_from::<ExtractAssetsAcceptedResponse>();
    c = c.schema_from::<ExtractAssetsStartBody>();
    c = c.schema_from::<GenerateAssetsBody>();
    c = c.schema_from::<GenerateNovelEventsBody>();
    c = c.schema_from::<GetScriptAgentPlanBody>();
    c = c.schema_from::<HarnessToolInfo>();
    c = c.schema_from::<HarnessToolsResponse>();
    c = c.schema_from::<HealthResponse>();
    c = c.schema_from::<JobKindSummary>();
    c = c.schema_from::<JobRow>();
    c = c.schema_from::<JobStatusSummary>();
    c = c.schema_from::<JobsPageResponse>();
    c = c.schema_from::<LegacyAssetsAddAssetsBody>();
    c = c.schema_from::<LegacyAssetsBatchDeleteBody>();
    c = c.schema_from::<LegacyAssetsBatchGenerationDataBody>();
    c = c.schema_from::<LegacyAssetsBatchGenerationDataItem>();
    c = c.schema_from::<LegacyAssetsBatchGenerationDataResponse>();
    c = c.schema_from::<LegacyAssetsDeleteBody>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiBody>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiChildItem>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiParentItem>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiResponse>();
    c = c.schema_from::<LegacyAssetsGetImageBody>();
    c = c.schema_from::<LegacyAssetsGetImageResponse>();
    c = c.schema_from::<LegacyAssetsGetImageTempAsset>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataBody>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataItem>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataResponse>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataVideoItem>();
    c = c.schema_from::<LegacyAssetsMutationResponse>();
    c = c.schema_from::<LegacyAssetsPollingImageAssetsBody>();
    c = c.schema_from::<LegacyAssetsPollingImageAssetsItem>();
    c = c.schema_from::<LegacyAssetsPollingPromptAssetsBody>();
    c = c.schema_from::<LegacyAssetsPollingPromptAssetsItem>();
    c = c.schema_from::<LegacyAssetsSaveAssetsBody>();
    c = c.schema_from::<LegacyAssetsUpdateAssetsBody>();
    c = c.schema_from::<LegacyAssetsUploadClipBody>();
    c = c.schema_from::<LegacyAssetsUploadClipResponse>();
    c = c.schema_from::<LegacyDirectorManualAddBody>();
    c = c.schema_from::<LegacyDirectorManualDataSlot>();
    c
}
