//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct ProductionExportImageShotRef;
impl PartialSchema for ProductionExportImageShotRef {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionExportImageShotRef")
    }
}
impl ToSchema for ProductionExportImageShotRef {}

pub struct ProductionFlowAssetDerivativeItem;
impl PartialSchema for ProductionFlowAssetDerivativeItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowAssetDerivativeItem")
    }
}
impl ToSchema for ProductionFlowAssetDerivativeItem {}

pub struct ProductionFlowAssetItem;
impl PartialSchema for ProductionFlowAssetItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowAssetItem")
    }
}
impl ToSchema for ProductionFlowAssetItem {}

pub struct ProductionFlowDataResponse;
impl PartialSchema for ProductionFlowDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowDataResponse")
    }
}
impl ToSchema for ProductionFlowDataResponse {}

pub struct ProductionFlowStoryboardItem;
impl PartialSchema for ProductionFlowStoryboardItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowStoryboardItem")
    }
}
impl ToSchema for ProductionFlowStoryboardItem {}

pub struct ProductionGetFlowDataBody;
impl PartialSchema for ProductionGetFlowDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionGetFlowDataBody")
    }
}
impl ToSchema for ProductionGetFlowDataBody {}

pub struct ProductionGetProductionDataResponse;
impl PartialSchema for ProductionGetProductionDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionGetProductionDataResponse")
    }
}
impl ToSchema for ProductionGetProductionDataResponse {}

pub struct ProductionLegacyJsonStubBody;
impl PartialSchema for ProductionLegacyJsonStubBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionLegacyJsonStubBody")
    }
}
impl ToSchema for ProductionLegacyJsonStubBody {}

pub struct ProductionSaveFlowDataBody;
impl PartialSchema for ProductionSaveFlowDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionSaveFlowDataBody")
    }
}
impl ToSchema for ProductionSaveFlowDataBody {}

pub struct ProductionStoryboardAddBody;
impl PartialSchema for ProductionStoryboardAddBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardAddBody")
    }
}
impl ToSchema for ProductionStoryboardAddBody {}

pub struct ProductionStoryboardAddResponse;
impl PartialSchema for ProductionStoryboardAddResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardAddResponse")
    }
}
impl ToSchema for ProductionStoryboardAddResponse {}

pub struct ProductionStoryboardBatchAddInfoBody;
impl PartialSchema for ProductionStoryboardBatchAddInfoBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchAddInfoBody")
    }
}
impl ToSchema for ProductionStoryboardBatchAddInfoBody {}

pub struct ProductionStoryboardBatchAddInfoItem;
impl PartialSchema for ProductionStoryboardBatchAddInfoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchAddInfoItem")
    }
}
impl ToSchema for ProductionStoryboardBatchAddInfoItem {}

pub struct ProductionStoryboardBatchAddInfoResponse;
impl PartialSchema for ProductionStoryboardBatchAddInfoResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchAddInfoResponse")
    }
}
impl ToSchema for ProductionStoryboardBatchAddInfoResponse {}

pub struct ProductionStoryboardBatchGenerateImageBody;
impl PartialSchema for ProductionStoryboardBatchGenerateImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchGenerateImageBody")
    }
}
impl ToSchema for ProductionStoryboardBatchGenerateImageBody {}

pub struct ProductionStoryboardBatchGenerateImageItem;
impl PartialSchema for ProductionStoryboardBatchGenerateImageItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchGenerateImageItem")
    }
}
impl ToSchema for ProductionStoryboardBatchGenerateImageItem {}

pub struct ProductionStoryboardBatchGenerateImageResponse;
impl PartialSchema for ProductionStoryboardBatchGenerateImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchGenerateImageResponse")
    }
}
impl ToSchema for ProductionStoryboardBatchGenerateImageResponse {}

pub struct ProductionStoryboardBundleItem;
impl PartialSchema for ProductionStoryboardBundleItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBundleItem")
    }
}
impl ToSchema for ProductionStoryboardBundleItem {}

pub struct ProductionStoryboardDownPreviewImageResponse;
impl PartialSchema for ProductionStoryboardDownPreviewImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardDownPreviewImageResponse")
    }
}
impl ToSchema for ProductionStoryboardDownPreviewImageResponse {}

pub struct ProductionStoryboardEditInfoBody;
impl PartialSchema for ProductionStoryboardEditInfoBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardEditInfoBody")
    }
}
impl ToSchema for ProductionStoryboardEditInfoBody {}

pub struct ProductionStoryboardEditInfoResponse;
impl PartialSchema for ProductionStoryboardEditInfoResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardEditInfoResponse")
    }
}
impl ToSchema for ProductionStoryboardEditInfoResponse {}

pub struct ProductionStoryboardIdBody;
impl PartialSchema for ProductionStoryboardIdBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardIdBody")
    }
}
impl ToSchema for ProductionStoryboardIdBody {}

pub struct ProductionStoryboardIdsBody;
impl PartialSchema for ProductionStoryboardIdsBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardIdsBody")
    }
}
impl ToSchema for ProductionStoryboardIdsBody {}

pub struct ProductionStoryboardListBody;
impl PartialSchema for ProductionStoryboardListBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardListBody")
    }
}
impl ToSchema for ProductionStoryboardListBody {}

pub struct ProductionStoryboardPreviewImageResponse;
impl PartialSchema for ProductionStoryboardPreviewImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardPreviewImageResponse")
    }
}
impl ToSchema for ProductionStoryboardPreviewImageResponse {}

pub struct ProductionStoryboardRemoveFrameResponse;
impl PartialSchema for ProductionStoryboardRemoveFrameResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardRemoveFrameResponse")
    }
}
impl ToSchema for ProductionStoryboardRemoveFrameResponse {}

pub struct ProductionStoryboardUpdateUrlBody;
impl PartialSchema for ProductionStoryboardUpdateUrlBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardUpdateUrlBody")
    }
}
impl ToSchema for ProductionStoryboardUpdateUrlBody {}

pub struct ProductionStoryboardUpdateUrlResponse;
impl PartialSchema for ProductionStoryboardUpdateUrlResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardUpdateUrlResponse")
    }
}
impl ToSchema for ProductionStoryboardUpdateUrlResponse {}

pub struct ProductionWorkbenchAddTrackBody;
impl PartialSchema for ProductionWorkbenchAddTrackBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchAddTrackBody")
    }
}
impl ToSchema for ProductionWorkbenchAddTrackBody {}

pub struct ProductionWorkbenchAddTrackResponse;
impl PartialSchema for ProductionWorkbenchAddTrackResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchAddTrackResponse")
    }
}
impl ToSchema for ProductionWorkbenchAddTrackResponse {}

pub struct ProductionWorkbenchDeleteTrackBody;
impl PartialSchema for ProductionWorkbenchDeleteTrackBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchDeleteTrackBody")
    }
}
impl ToSchema for ProductionWorkbenchDeleteTrackBody {}

pub struct ProductionWorkbenchDeleteTrackResponse;
impl PartialSchema for ProductionWorkbenchDeleteTrackResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchDeleteTrackResponse")
    }
}
impl ToSchema for ProductionWorkbenchDeleteTrackResponse {}

pub struct ProductionWorkbenchDeleteVideoBody;
impl PartialSchema for ProductionWorkbenchDeleteVideoBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchDeleteVideoBody")
    }
}
impl ToSchema for ProductionWorkbenchDeleteVideoBody {}

pub struct ProductionWorkbenchDeleteVideoResponse;
impl PartialSchema for ProductionWorkbenchDeleteVideoResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchDeleteVideoResponse")
    }
}
impl ToSchema for ProductionWorkbenchDeleteVideoResponse {}

pub struct ProductionWorkbenchGenerateVideoBody;
impl PartialSchema for ProductionWorkbenchGenerateVideoBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGenerateVideoBody")
    }
}
impl ToSchema for ProductionWorkbenchGenerateVideoBody {}

pub struct ProductionWorkbenchGenerateVideoPromptBody;
impl PartialSchema for ProductionWorkbenchGenerateVideoPromptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGenerateVideoPromptBody")
    }
}
impl ToSchema for ProductionWorkbenchGenerateVideoPromptBody {}

pub struct ProductionWorkbenchGenerateVideoPromptResponse;
impl PartialSchema for ProductionWorkbenchGenerateVideoPromptResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGenerateVideoPromptResponse")
    }
}
impl ToSchema for ProductionWorkbenchGenerateVideoPromptResponse {}

pub struct ProductionWorkbenchGenerateVideoUploadItem;
impl PartialSchema for ProductionWorkbenchGenerateVideoUploadItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGenerateVideoUploadItem")
    }
}
impl ToSchema for ProductionWorkbenchGenerateVideoUploadItem {}

pub struct ProductionWorkbenchGetGenerateDataBody;
impl PartialSchema for ProductionWorkbenchGetGenerateDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGetGenerateDataBody")
    }
}
impl ToSchema for ProductionWorkbenchGetGenerateDataBody {}

pub struct ProductionWorkbenchGetGenerateDataResponse;
impl PartialSchema for ProductionWorkbenchGetGenerateDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGetGenerateDataResponse")
    }
}
impl ToSchema for ProductionWorkbenchGetGenerateDataResponse {}

pub struct ProductionWorkbenchGetVideoListBody;
impl PartialSchema for ProductionWorkbenchGetVideoListBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGetVideoListBody")
    }
}
impl ToSchema for ProductionWorkbenchGetVideoListBody {}

pub struct ProductionWorkbenchGetVideoListResponse;
impl PartialSchema for ProductionWorkbenchGetVideoListResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGetVideoListResponse")
    }
}
impl ToSchema for ProductionWorkbenchGetVideoListResponse {}

pub struct ProductionWorkbenchSelectVideoBody;
impl PartialSchema for ProductionWorkbenchSelectVideoBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchSelectVideoBody")
    }
}
impl ToSchema for ProductionWorkbenchSelectVideoBody {}

pub struct ProductionWorkbenchSelectVideoResponse;
impl PartialSchema for ProductionWorkbenchSelectVideoResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchSelectVideoResponse")
    }
}
impl ToSchema for ProductionWorkbenchSelectVideoResponse {}

pub struct ProductionWorkbenchVideoModelDetailResponse;
impl PartialSchema for ProductionWorkbenchVideoModelDetailResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchVideoModelDetailResponse")
    }
}
impl ToSchema for ProductionWorkbenchVideoModelDetailResponse {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<ProductionExportImageShotRef>();
    c = c.schema_from::<ProductionFlowAssetDerivativeItem>();
    c = c.schema_from::<ProductionFlowAssetItem>();
    c = c.schema_from::<ProductionFlowDataResponse>();
    c = c.schema_from::<ProductionFlowStoryboardItem>();
    c = c.schema_from::<ProductionGetFlowDataBody>();
    c = c.schema_from::<ProductionGetProductionDataResponse>();
    c = c.schema_from::<ProductionLegacyJsonStubBody>();
    c = c.schema_from::<ProductionSaveFlowDataBody>();
    c = c.schema_from::<ProductionStoryboardAddBody>();
    c = c.schema_from::<ProductionStoryboardAddResponse>();
    c = c.schema_from::<ProductionStoryboardBatchAddInfoBody>();
    c = c.schema_from::<ProductionStoryboardBatchAddInfoItem>();
    c = c.schema_from::<ProductionStoryboardBatchAddInfoResponse>();
    c = c.schema_from::<ProductionStoryboardBatchGenerateImageBody>();
    c = c.schema_from::<ProductionStoryboardBatchGenerateImageItem>();
    c = c.schema_from::<ProductionStoryboardBatchGenerateImageResponse>();
    c = c.schema_from::<ProductionStoryboardBundleItem>();
    c = c.schema_from::<ProductionStoryboardDownPreviewImageResponse>();
    c = c.schema_from::<ProductionStoryboardEditInfoBody>();
    c = c.schema_from::<ProductionStoryboardEditInfoResponse>();
    c = c.schema_from::<ProductionStoryboardIdBody>();
    c = c.schema_from::<ProductionStoryboardIdsBody>();
    c = c.schema_from::<ProductionStoryboardListBody>();
    c = c.schema_from::<ProductionStoryboardPreviewImageResponse>();
    c = c.schema_from::<ProductionStoryboardRemoveFrameResponse>();
    c = c.schema_from::<ProductionStoryboardUpdateUrlBody>();
    c = c.schema_from::<ProductionStoryboardUpdateUrlResponse>();
    c = c.schema_from::<ProductionWorkbenchAddTrackBody>();
    c = c.schema_from::<ProductionWorkbenchAddTrackResponse>();
    c = c.schema_from::<ProductionWorkbenchDeleteTrackBody>();
    c = c.schema_from::<ProductionWorkbenchDeleteTrackResponse>();
    c = c.schema_from::<ProductionWorkbenchDeleteVideoBody>();
    c = c.schema_from::<ProductionWorkbenchDeleteVideoResponse>();
    c = c.schema_from::<ProductionWorkbenchGenerateVideoBody>();
    c = c.schema_from::<ProductionWorkbenchGenerateVideoPromptBody>();
    c = c.schema_from::<ProductionWorkbenchGenerateVideoPromptResponse>();
    c = c.schema_from::<ProductionWorkbenchGenerateVideoUploadItem>();
    c = c.schema_from::<ProductionWorkbenchGetGenerateDataBody>();
    c = c.schema_from::<ProductionWorkbenchGetGenerateDataResponse>();
    c = c.schema_from::<ProductionWorkbenchGetVideoListBody>();
    c = c.schema_from::<ProductionWorkbenchGetVideoListResponse>();
    c = c.schema_from::<ProductionWorkbenchSelectVideoBody>();
    c = c.schema_from::<ProductionWorkbenchSelectVideoResponse>();
    c = c.schema_from::<ProductionWorkbenchVideoModelDetailResponse>();
    c
}
