//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct QueryAgentMemoryBody;
impl PartialSchema for QueryAgentMemoryBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("QueryAgentMemoryBody")
    }
}
impl ToSchema for QueryAgentMemoryBody {}

pub struct RateLimitError;
impl PartialSchema for RateLimitError {
    fn schema() -> RefOr<Schema> {
        legacy_pick("RateLimitError")
    }
}
impl ToSchema for RateLimitError {}

pub struct ReadyResponse;
impl PartialSchema for ReadyResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ReadyResponse")
    }
}
impl ToSchema for ReadyResponse {}

pub struct ScriptAgentTypeV1;
impl PartialSchema for ScriptAgentTypeV1 {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptAgentTypeV1")
    }
}
impl ToSchema for ScriptAgentTypeV1 {}

pub struct ScriptBrief;
impl PartialSchema for ScriptBrief {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptBrief")
    }
}
impl ToSchema for ScriptBrief {}

pub struct ScriptExtractStatePollBody;
impl PartialSchema for ScriptExtractStatePollBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptExtractStatePollBody")
    }
}
impl ToSchema for ScriptExtractStatePollBody {}

pub struct ScriptExtractStatePollRow;
impl PartialSchema for ScriptExtractStatePollRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptExtractStatePollRow")
    }
}
impl ToSchema for ScriptExtractStatePollRow {}

pub struct ScriptRow;
impl PartialSchema for ScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptRow")
    }
}
impl ToSchema for ScriptRow {}

pub struct ScriptsGetScriptApiNameBody;
impl PartialSchema for ScriptsGetScriptApiNameBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptsGetScriptApiNameBody")
    }
}
impl ToSchema for ScriptsGetScriptApiNameBody {}

pub struct SetScriptAgentPlanBody;
impl PartialSchema for SetScriptAgentPlanBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SetScriptAgentPlanBody")
    }
}
impl ToSchema for SetScriptAgentPlanBody {}

pub struct SetScriptAgentPlanData;
impl PartialSchema for SetScriptAgentPlanData {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SetScriptAgentPlanData")
    }
}
impl ToSchema for SetScriptAgentPlanData {}

pub struct SetScriptAgentPlanScriptRow;
impl PartialSchema for SetScriptAgentPlanScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SetScriptAgentPlanScriptRow")
    }
}
impl ToSchema for SetScriptAgentPlanScriptRow {}

pub struct SettingsClearAgentMemoriesBody;
impl PartialSchema for SettingsClearAgentMemoriesBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SettingsClearAgentMemoriesBody")
    }
}
impl ToSchema for SettingsClearAgentMemoriesBody {}

pub struct SkillContentResponse;
impl PartialSchema for SkillContentResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SkillContentResponse")
    }
}
impl ToSchema for SkillContentResponse {}

pub struct SkillContentWriteRequest;
impl PartialSchema for SkillContentWriteRequest {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SkillContentWriteRequest")
    }
}
impl ToSchema for SkillContentWriteRequest {}

pub struct SkillFileMeta;
impl PartialSchema for SkillFileMeta {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SkillFileMeta")
    }
}
impl ToSchema for SkillFileMeta {}

pub struct SkillsSummaryResponse;
impl PartialSchema for SkillsSummaryResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SkillsSummaryResponse")
    }
}
impl ToSchema for SkillsSummaryResponse {}

pub struct StagePassRateItem;
impl PartialSchema for StagePassRateItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("StagePassRateItem")
    }
}
impl ToSchema for StagePassRateItem {}

pub struct StoreVendorCredentialBody;
impl PartialSchema for StoreVendorCredentialBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("StoreVendorCredentialBody")
    }
}
impl ToSchema for StoreVendorCredentialBody {}

pub struct StoryboardRow;
impl PartialSchema for StoryboardRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("StoryboardRow")
    }
}
impl ToSchema for StoryboardRow {}

pub struct SwitchAiDevToolPutRequest;
impl PartialSchema for SwitchAiDevToolPutRequest {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SwitchAiDevToolPutRequest")
    }
}
impl ToSchema for SwitchAiDevToolPutRequest {}

pub struct SwitchAiDevToolResponse;
impl PartialSchema for SwitchAiDevToolResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("SwitchAiDevToolResponse")
    }
}
impl ToSchema for SwitchAiDevToolResponse {}

pub struct TextModelDefaultResponse;
impl PartialSchema for TextModelDefaultResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("TextModelDefaultResponse")
    }
}
impl ToSchema for TextModelDefaultResponse {}

pub struct UpdateNovelEventBody;
impl PartialSchema for UpdateNovelEventBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateNovelEventBody")
    }
}
impl ToSchema for UpdateNovelEventBody {}

pub struct UpdateScriptAgentDataBody;
impl PartialSchema for UpdateScriptAgentDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateScriptAgentDataBody")
    }
}
impl ToSchema for UpdateScriptAgentDataBody {}

pub struct UpdateScriptAgentDataPayload;
impl PartialSchema for UpdateScriptAgentDataPayload {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateScriptAgentDataPayload")
    }
}
impl ToSchema for UpdateScriptAgentDataPayload {}

pub struct UpdateScriptAgentScriptRow;
impl PartialSchema for UpdateScriptAgentScriptRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UpdateScriptAgentScriptRow")
    }
}
impl ToSchema for UpdateScriptAgentScriptRow {}

pub struct UsageSummaryResponse;
impl PartialSchema for UsageSummaryResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("UsageSummaryResponse")
    }
}
impl ToSchema for UsageSummaryResponse {}

pub struct VendorAddBody;
impl PartialSchema for VendorAddBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorAddBody")
    }
}
impl ToSchema for VendorAddBody {}

pub struct VendorCatalogSummary;
impl PartialSchema for VendorCatalogSummary {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorCatalogSummary")
    }
}
impl ToSchema for VendorCatalogSummary {}

pub struct VendorCodeFromLinkBody;
impl PartialSchema for VendorCodeFromLinkBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorCodeFromLinkBody")
    }
}
impl ToSchema for VendorCodeFromLinkBody {}

pub struct VendorConfig;
impl PartialSchema for VendorConfig {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorConfig")
    }
}
impl ToSchema for VendorConfig {}

pub struct VendorConfigEntry;
impl PartialSchema for VendorConfigEntry {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorConfigEntry")
    }
}
impl ToSchema for VendorConfigEntry {}

pub struct VendorCredentialResponse;
impl PartialSchema for VendorCredentialResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorCredentialResponse")
    }
}
impl ToSchema for VendorCredentialResponse {}

pub struct VendorEnableBody;
impl PartialSchema for VendorEnableBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorEnableBody")
    }
}
impl ToSchema for VendorEnableBody {}

pub struct VendorEnableResponse;
impl PartialSchema for VendorEnableResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorEnableResponse")
    }
}
impl ToSchema for VendorEnableResponse {}

pub struct VendorIdBody;
impl PartialSchema for VendorIdBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorIdBody")
    }
}
impl ToSchema for VendorIdBody {}

pub struct VendorLinkResponse;
impl PartialSchema for VendorLinkResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorLinkResponse")
    }
}
impl ToSchema for VendorLinkResponse {}

pub struct VendorModelTestBody;
impl PartialSchema for VendorModelTestBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorModelTestBody")
    }
}
impl ToSchema for VendorModelTestBody {}

pub struct VendorMutationResponse;
impl PartialSchema for VendorMutationResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorMutationResponse")
    }
}
impl ToSchema for VendorMutationResponse {}

pub struct VendorSummaryItem;
impl PartialSchema for VendorSummaryItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorSummaryItem")
    }
}
impl ToSchema for VendorSummaryItem {}

pub struct VendorUpdateBody;
impl PartialSchema for VendorUpdateBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorUpdateBody")
    }
}
impl ToSchema for VendorUpdateBody {}

pub struct VendorUpdateCodeBody;
impl PartialSchema for VendorUpdateCodeBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorUpdateCodeBody")
    }
}
impl ToSchema for VendorUpdateCodeBody {}

pub struct VendorUpdateResponse;
impl PartialSchema for VendorUpdateResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorUpdateResponse")
    }
}
impl ToSchema for VendorUpdateResponse {}

pub struct VendorsSummaryResponse;
impl PartialSchema for VendorsSummaryResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("VendorsSummaryResponse")
    }
}
impl ToSchema for VendorsSummaryResponse {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<QueryAgentMemoryBody>();
    c = c.schema_from::<RateLimitError>();
    c = c.schema_from::<ReadyResponse>();
    c = c.schema_from::<ScriptAgentTypeV1>();
    c = c.schema_from::<ScriptBrief>();
    c = c.schema_from::<ScriptExtractStatePollBody>();
    c = c.schema_from::<ScriptExtractStatePollRow>();
    c = c.schema_from::<ScriptRow>();
    c = c.schema_from::<ScriptsGetScriptApiNameBody>();
    c = c.schema_from::<SetScriptAgentPlanBody>();
    c = c.schema_from::<SetScriptAgentPlanData>();
    c = c.schema_from::<SetScriptAgentPlanScriptRow>();
    c = c.schema_from::<SettingsClearAgentMemoriesBody>();
    c = c.schema_from::<SkillContentResponse>();
    c = c.schema_from::<SkillContentWriteRequest>();
    c = c.schema_from::<SkillFileMeta>();
    c = c.schema_from::<SkillsSummaryResponse>();
    c = c.schema_from::<StagePassRateItem>();
    c = c.schema_from::<StoreVendorCredentialBody>();
    c = c.schema_from::<StoryboardRow>();
    c = c.schema_from::<SwitchAiDevToolPutRequest>();
    c = c.schema_from::<SwitchAiDevToolResponse>();
    c = c.schema_from::<TextModelDefaultResponse>();
    c = c.schema_from::<UpdateNovelEventBody>();
    c = c.schema_from::<UpdateScriptAgentDataBody>();
    c = c.schema_from::<UpdateScriptAgentDataPayload>();
    c = c.schema_from::<UpdateScriptAgentScriptRow>();
    c = c.schema_from::<UsageSummaryResponse>();
    c = c.schema_from::<VendorAddBody>();
    c = c.schema_from::<VendorCatalogSummary>();
    c = c.schema_from::<VendorCodeFromLinkBody>();
    c = c.schema_from::<VendorConfig>();
    c = c.schema_from::<VendorConfigEntry>();
    c = c.schema_from::<VendorCredentialResponse>();
    c = c.schema_from::<VendorEnableBody>();
    c = c.schema_from::<VendorEnableResponse>();
    c = c.schema_from::<VendorIdBody>();
    c = c.schema_from::<VendorLinkResponse>();
    c = c.schema_from::<VendorModelTestBody>();
    c = c.schema_from::<VendorMutationResponse>();
    c = c.schema_from::<VendorSummaryItem>();
    c = c.schema_from::<VendorUpdateBody>();
    c = c.schema_from::<VendorUpdateCodeBody>();
    c = c.schema_from::<VendorUpdateResponse>();
    c = c.schema_from::<VendorsSummaryResponse>();
    c
}
