//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct MemoryHistoryItem;
impl PartialSchema for MemoryHistoryItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MemoryHistoryItem")
    }
}
impl ToSchema for MemoryHistoryItem {}

pub struct MemoryMarkdownBlock;
impl PartialSchema for MemoryMarkdownBlock {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MemoryMarkdownBlock")
    }
}
impl ToSchema for MemoryMarkdownBlock {}

pub struct ModelDetailResponse;
impl PartialSchema for ModelDetailResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ModelDetailResponse")
    }
}
impl ToSchema for ModelDetailResponse {}

pub struct ModelListEntry;
impl PartialSchema for ModelListEntry {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ModelListEntry")
    }
}
impl ToSchema for ModelListEntry {}

pub struct NovelEventCreateResponse;
impl PartialSchema for NovelEventCreateResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelEventCreateResponse")
    }
}
impl ToSchema for NovelEventCreateResponse {}

pub struct NovelEventListResponse;
impl PartialSchema for NovelEventListResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelEventListResponse")
    }
}
impl ToSchema for NovelEventListResponse {}

pub struct NovelEventOkResponse;
impl PartialSchema for NovelEventOkResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelEventOkResponse")
    }
}
impl ToSchema for NovelEventOkResponse {}

pub struct NovelEventWithChapters;
impl PartialSchema for NovelEventWithChapters {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelEventWithChapters")
    }
}
impl ToSchema for NovelEventWithChapters {}

pub struct NovelRow;
impl PartialSchema for NovelRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelRow")
    }
}
impl ToSchema for NovelRow {}

pub struct PatchArtStyleBody;
impl PartialSchema for PatchArtStyleBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchArtStyleBody")
    }
}
impl ToSchema for PatchArtStyleBody {}

pub struct PatchAssetBody;
impl PartialSchema for PatchAssetBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchAssetBody")
    }
}
impl ToSchema for PatchAssetBody {}

pub struct PatchAssetImageBody;
impl PartialSchema for PatchAssetImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchAssetImageBody")
    }
}
impl ToSchema for PatchAssetImageBody {}

pub struct PatchNovelBody;
impl PartialSchema for PatchNovelBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchNovelBody")
    }
}
impl ToSchema for PatchNovelBody {}

pub struct PatchProjectBody;
impl PartialSchema for PatchProjectBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchProjectBody")
    }
}
impl ToSchema for PatchProjectBody {}

pub struct PatchPromptBody;
impl PartialSchema for PatchPromptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchPromptBody")
    }
}
impl ToSchema for PatchPromptBody {}

pub struct PatchScriptBody;
impl PartialSchema for PatchScriptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchScriptBody")
    }
}
impl ToSchema for PatchScriptBody {}

pub struct PatchStoryboardBody;
impl PartialSchema for PatchStoryboardBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchStoryboardBody")
    }
}
impl ToSchema for PatchStoryboardBody {}

pub struct PatchTextModelDefaultBody;
impl PartialSchema for PatchTextModelDefaultBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PatchTextModelDefaultBody")
    }
}
impl ToSchema for PatchTextModelDefaultBody {}

pub struct PingResponse;
impl PartialSchema for PingResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PingResponse")
    }
}
impl ToSchema for PingResponse {}

pub struct PolishAssetsPromptBody;
impl PartialSchema for PolishAssetsPromptBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("PolishAssetsPromptBody")
    }
}
impl ToSchema for PolishAssetsPromptBody {}

pub struct ProductionAssetDataItem;
impl PartialSchema for ProductionAssetDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetDataItem")
    }
}
impl ToSchema for ProductionAssetDataItem {}

pub struct ProductionAssetImageStatus;
impl PartialSchema for ProductionAssetImageStatus {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetImageStatus")
    }
}
impl ToSchema for ProductionAssetImageStatus {}

pub struct ProductionAssetsBatchGenerateImageBody;
impl PartialSchema for ProductionAssetsBatchGenerateImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsBatchGenerateImageBody")
    }
}
impl ToSchema for ProductionAssetsBatchGenerateImageBody {}

pub struct ProductionAssetsBatchGenerateImageResponse;
impl PartialSchema for ProductionAssetsBatchGenerateImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsBatchGenerateImageResponse")
    }
}
impl ToSchema for ProductionAssetsBatchGenerateImageResponse {}

pub struct ProductionAssetsDeleteDerivativeBody;
impl PartialSchema for ProductionAssetsDeleteDerivativeBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsDeleteDerivativeBody")
    }
}
impl ToSchema for ProductionAssetsDeleteDerivativeBody {}

pub struct ProductionAssetsDeleteDerivativeResponse;
impl PartialSchema for ProductionAssetsDeleteDerivativeResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsDeleteDerivativeResponse")
    }
}
impl ToSchema for ProductionAssetsDeleteDerivativeResponse {}

pub struct ProductionAssetsGetDataBody;
impl PartialSchema for ProductionAssetsGetDataBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsGetDataBody")
    }
}
impl ToSchema for ProductionAssetsGetDataBody {}

pub struct ProductionAssetsGetDataResponse;
impl PartialSchema for ProductionAssetsGetDataResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsGetDataResponse")
    }
}
impl ToSchema for ProductionAssetsGetDataResponse {}

pub struct ProductionAssetsPollingImageBody;
impl PartialSchema for ProductionAssetsPollingImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsPollingImageBody")
    }
}
impl ToSchema for ProductionAssetsPollingImageBody {}

pub struct ProductionAssetsPollingImageResponse;
impl PartialSchema for ProductionAssetsPollingImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsPollingImageResponse")
    }
}
impl ToSchema for ProductionAssetsPollingImageResponse {}

pub struct ProductionAssetsUpdateUrlBody;
impl PartialSchema for ProductionAssetsUpdateUrlBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsUpdateUrlBody")
    }
}
impl ToSchema for ProductionAssetsUpdateUrlBody {}

pub struct ProductionAssetsUpdateUrlResponse;
impl PartialSchema for ProductionAssetsUpdateUrlResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetsUpdateUrlResponse")
    }
}
impl ToSchema for ProductionAssetsUpdateUrlResponse {}

pub struct ProductionEditImageDefaultModelResponse;
impl PartialSchema for ProductionEditImageDefaultModelResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageDefaultModelResponse")
    }
}
impl ToSchema for ProductionEditImageDefaultModelResponse {}

pub struct ProductionEditImageFlowStep;
impl PartialSchema for ProductionEditImageFlowStep {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageFlowStep")
    }
}
impl ToSchema for ProductionEditImageFlowStep {}

pub struct ProductionEditImageFlowStepInput;
impl PartialSchema for ProductionEditImageFlowStepInput {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageFlowStepInput")
    }
}
impl ToSchema for ProductionEditImageFlowStepInput {}

pub struct ProductionEditImageGenerateFlowImageBody;
impl PartialSchema for ProductionEditImageGenerateFlowImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageGenerateFlowImageBody")
    }
}
impl ToSchema for ProductionEditImageGenerateFlowImageBody {}

pub struct ProductionEditImageGenerateFlowImageResponse;
impl PartialSchema for ProductionEditImageGenerateFlowImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageGenerateFlowImageResponse")
    }
}
impl ToSchema for ProductionEditImageGenerateFlowImageResponse {}

pub struct ProductionEditImageGetFlowResponse;
impl PartialSchema for ProductionEditImageGetFlowResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageGetFlowResponse")
    }
}
impl ToSchema for ProductionEditImageGetFlowResponse {}

pub struct ProductionEditImageSaveFlowBody;
impl PartialSchema for ProductionEditImageSaveFlowBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageSaveFlowBody")
    }
}
impl ToSchema for ProductionEditImageSaveFlowBody {}

pub struct ProductionEditImageSaveFlowResponse;
impl PartialSchema for ProductionEditImageSaveFlowResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageSaveFlowResponse")
    }
}
impl ToSchema for ProductionEditImageSaveFlowResponse {}

pub struct ProductionEditImageUpdateFlowBody;
impl PartialSchema for ProductionEditImageUpdateFlowBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageUpdateFlowBody")
    }
}
impl ToSchema for ProductionEditImageUpdateFlowBody {}

pub struct ProductionEditImageUpdateFlowResponse;
impl PartialSchema for ProductionEditImageUpdateFlowResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageUpdateFlowResponse")
    }
}
impl ToSchema for ProductionEditImageUpdateFlowResponse {}

pub struct ProductionEditImageUploadImageBody;
impl PartialSchema for ProductionEditImageUploadImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageUploadImageBody")
    }
}
impl ToSchema for ProductionEditImageUploadImageBody {}

pub struct ProductionEditImageUploadImageResponse;
impl PartialSchema for ProductionEditImageUploadImageResponse {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageUploadImageResponse")
    }
}
impl ToSchema for ProductionEditImageUploadImageResponse {}

pub struct ProductionExportImageBody;
impl PartialSchema for ProductionExportImageBody {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionExportImageBody")
    }
}
impl ToSchema for ProductionExportImageBody {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<MemoryHistoryItem>();
    c = c.schema_from::<MemoryMarkdownBlock>();
    c = c.schema_from::<ModelDetailResponse>();
    c = c.schema_from::<ModelListEntry>();
    c = c.schema_from::<NovelEventCreateResponse>();
    c = c.schema_from::<NovelEventListResponse>();
    c = c.schema_from::<NovelEventOkResponse>();
    c = c.schema_from::<NovelEventWithChapters>();
    c = c.schema_from::<NovelRow>();
    c = c.schema_from::<PatchArtStyleBody>();
    c = c.schema_from::<PatchAssetBody>();
    c = c.schema_from::<PatchAssetImageBody>();
    c = c.schema_from::<PatchNovelBody>();
    c = c.schema_from::<PatchProjectBody>();
    c = c.schema_from::<PatchPromptBody>();
    c = c.schema_from::<PatchScriptBody>();
    c = c.schema_from::<PatchStoryboardBody>();
    c = c.schema_from::<PatchTextModelDefaultBody>();
    c = c.schema_from::<PingResponse>();
    c = c.schema_from::<PolishAssetsPromptBody>();
    c = c.schema_from::<ProductionAssetDataItem>();
    c = c.schema_from::<ProductionAssetImageStatus>();
    c = c.schema_from::<ProductionAssetsBatchGenerateImageBody>();
    c = c.schema_from::<ProductionAssetsBatchGenerateImageResponse>();
    c = c.schema_from::<ProductionAssetsDeleteDerivativeBody>();
    c = c.schema_from::<ProductionAssetsDeleteDerivativeResponse>();
    c = c.schema_from::<ProductionAssetsGetDataBody>();
    c = c.schema_from::<ProductionAssetsGetDataResponse>();
    c = c.schema_from::<ProductionAssetsPollingImageBody>();
    c = c.schema_from::<ProductionAssetsPollingImageResponse>();
    c = c.schema_from::<ProductionAssetsUpdateUrlBody>();
    c = c.schema_from::<ProductionAssetsUpdateUrlResponse>();
    c = c.schema_from::<ProductionEditImageDefaultModelResponse>();
    c = c.schema_from::<ProductionEditImageFlowStep>();
    c = c.schema_from::<ProductionEditImageFlowStepInput>();
    c = c.schema_from::<ProductionEditImageGenerateFlowImageBody>();
    c = c.schema_from::<ProductionEditImageGenerateFlowImageResponse>();
    c = c.schema_from::<ProductionEditImageGetFlowResponse>();
    c = c.schema_from::<ProductionEditImageSaveFlowBody>();
    c = c.schema_from::<ProductionEditImageSaveFlowResponse>();
    c = c.schema_from::<ProductionEditImageUpdateFlowBody>();
    c = c.schema_from::<ProductionEditImageUpdateFlowResponse>();
    c = c.schema_from::<ProductionEditImageUploadImageBody>();
    c = c.schema_from::<ProductionEditImageUploadImageResponse>();
    c = c.schema_from::<ProductionExportImageBody>();
    c
}
