//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

#![allow(dead_code)]

use utoipa::openapi::{schema::Schema, RefOr};
use utoipa::{PartialSchema, ToSchema};

use super::inline::legacy_pick;

pub struct AboutCheckUpdateSource;
impl PartialSchema for AboutCheckUpdateSource {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AboutCheckUpdateSource")
    }
}
impl ToSchema for AboutCheckUpdateSource {}

pub struct AssetGenTypeV1;
impl PartialSchema for AssetGenTypeV1 {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetGenTypeV1")
    }
}
impl ToSchema for AssetGenTypeV1 {}

pub struct AssetImageListItem;
impl PartialSchema for AssetImageListItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetImageListItem")
    }
}
impl ToSchema for AssetImageListItem {}

pub struct AssetImageRow;
impl PartialSchema for AssetImageRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetImageRow")
    }
}
impl ToSchema for AssetImageRow {}

pub struct AssetRow;
impl PartialSchema for AssetRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("AssetRow")
    }
}
impl ToSchema for AssetRow {}

pub struct BatchAddScriptItem;
impl PartialSchema for BatchAddScriptItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchAddScriptItem")
    }
}
impl ToSchema for BatchAddScriptItem {}

pub struct BatchGenerateImageItem;
impl PartialSchema for BatchGenerateImageItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchGenerateImageItem")
    }
}
impl ToSchema for BatchGenerateImageItem {}

pub struct BatchPolishAssetsItem;
impl PartialSchema for BatchPolishAssetsItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("BatchPolishAssetsItem")
    }
}
impl ToSchema for BatchPolishAssetsItem {}

pub struct CornerScapeAssetItem;
impl PartialSchema for CornerScapeAssetItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeAssetItem")
    }
}
impl ToSchema for CornerScapeAssetItem {}

pub struct CornerScapeHistoryImage;
impl PartialSchema for CornerScapeHistoryImage {
    fn schema() -> RefOr<Schema> {
        legacy_pick("CornerScapeHistoryImage")
    }
}
impl ToSchema for CornerScapeHistoryImage {}

pub struct JobRow;
impl PartialSchema for JobRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("JobRow")
    }
}
impl ToSchema for JobRow {}

pub struct LegacyAssetsBatchGenerationDataItem;
impl PartialSchema for LegacyAssetsBatchGenerationDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsBatchGenerationDataItem")
    }
}
impl ToSchema for LegacyAssetsBatchGenerationDataItem {}

pub struct LegacyAssetsGetAssetsApiChildItem;
impl PartialSchema for LegacyAssetsGetAssetsApiChildItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiChildItem")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiChildItem {}

pub struct LegacyAssetsGetAssetsApiParentItem;
impl PartialSchema for LegacyAssetsGetAssetsApiParentItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetAssetsApiParentItem")
    }
}
impl ToSchema for LegacyAssetsGetAssetsApiParentItem {}

pub struct LegacyAssetsGetImageTempAsset;
impl PartialSchema for LegacyAssetsGetImageTempAsset {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetImageTempAsset")
    }
}
impl ToSchema for LegacyAssetsGetImageTempAsset {}

pub struct LegacyAssetsGetMaterialDataItem;
impl PartialSchema for LegacyAssetsGetMaterialDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataItem")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataItem {}

pub struct LegacyAssetsGetMaterialDataVideoItem;
impl PartialSchema for LegacyAssetsGetMaterialDataVideoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyAssetsGetMaterialDataVideoItem")
    }
}
impl ToSchema for LegacyAssetsGetMaterialDataVideoItem {}

pub struct LegacyDirectorManualDataSlot;
impl PartialSchema for LegacyDirectorManualDataSlot {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualDataSlot")
    }
}
impl ToSchema for LegacyDirectorManualDataSlot {}

pub struct LegacyDirectorManualSlotRow;
impl PartialSchema for LegacyDirectorManualSlotRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualSlotRow")
    }
}
impl ToSchema for LegacyDirectorManualSlotRow {}

pub struct LegacyDirectorManualStyleRow;
impl PartialSchema for LegacyDirectorManualStyleRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyDirectorManualStyleRow")
    }
}
impl ToSchema for LegacyDirectorManualStyleRow {}

pub struct LegacyNovelAddNovelItem;
impl PartialSchema for LegacyNovelAddNovelItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelAddNovelItem")
    }
}
impl ToSchema for LegacyNovelAddNovelItem {}

pub struct LegacyNovelEventRow;
impl PartialSchema for LegacyNovelEventRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventRow")
    }
}
impl ToSchema for LegacyNovelEventRow {}

pub struct LegacyNovelEventStateItem;
impl PartialSchema for LegacyNovelEventStateItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelEventStateItem")
    }
}
impl ToSchema for LegacyNovelEventStateItem {}

pub struct LegacyNovelGetNovelPageRow;
impl PartialSchema for LegacyNovelGetNovelPageRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelGetNovelPageRow")
    }
}
impl ToSchema for LegacyNovelGetNovelPageRow {}

pub struct LegacyNovelIndexItem;
impl PartialSchema for LegacyNovelIndexItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyNovelIndexItem")
    }
}
impl ToSchema for LegacyNovelIndexItem {}

pub struct LegacyScriptRelatedAssetBrief;
impl PartialSchema for LegacyScriptRelatedAssetBrief {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyScriptRelatedAssetBrief")
    }
}
impl ToSchema for LegacyScriptRelatedAssetBrief {}

pub struct LegacyScriptsGetScriptApiItem;
impl PartialSchema for LegacyScriptsGetScriptApiItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("LegacyScriptsGetScriptApiItem")
    }
}
impl ToSchema for LegacyScriptsGetScriptApiItem {}

pub struct MemoryMarkdownBlock;
impl PartialSchema for MemoryMarkdownBlock {
    fn schema() -> RefOr<Schema> {
        legacy_pick("MemoryMarkdownBlock")
    }
}
impl ToSchema for MemoryMarkdownBlock {}

pub struct NovelEventWithChapters;
impl PartialSchema for NovelEventWithChapters {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelEventWithChapters")
    }
}
impl ToSchema for NovelEventWithChapters {}

pub struct NovelRow;
impl PartialSchema for NovelRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("NovelRow")
    }
}
impl ToSchema for NovelRow {}

pub struct ProductionAssetDataItem;
impl PartialSchema for ProductionAssetDataItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetDataItem")
    }
}
impl ToSchema for ProductionAssetDataItem {}

pub struct ProductionAssetImageStatus;
impl PartialSchema for ProductionAssetImageStatus {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionAssetImageStatus")
    }
}
impl ToSchema for ProductionAssetImageStatus {}

pub struct ProductionEditImageFlowStep;
impl PartialSchema for ProductionEditImageFlowStep {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageFlowStep")
    }
}
impl ToSchema for ProductionEditImageFlowStep {}

pub struct ProductionEditImageFlowStepInput;
impl PartialSchema for ProductionEditImageFlowStepInput {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionEditImageFlowStepInput")
    }
}
impl ToSchema for ProductionEditImageFlowStepInput {}

pub struct ProductionExportImageShotRef;
impl PartialSchema for ProductionExportImageShotRef {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionExportImageShotRef")
    }
}
impl ToSchema for ProductionExportImageShotRef {}

pub struct ProductionFlowAssetDerivativeItem;
impl PartialSchema for ProductionFlowAssetDerivativeItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowAssetDerivativeItem")
    }
}
impl ToSchema for ProductionFlowAssetDerivativeItem {}

pub struct ProductionFlowAssetItem;
impl PartialSchema for ProductionFlowAssetItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowAssetItem")
    }
}
impl ToSchema for ProductionFlowAssetItem {}

pub struct ProductionFlowStoryboardItem;
impl PartialSchema for ProductionFlowStoryboardItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionFlowStoryboardItem")
    }
}
impl ToSchema for ProductionFlowStoryboardItem {}

pub struct ProductionStoryboardBatchAddInfoItem;
impl PartialSchema for ProductionStoryboardBatchAddInfoItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchAddInfoItem")
    }
}
impl ToSchema for ProductionStoryboardBatchAddInfoItem {}

pub struct ProductionStoryboardBatchGenerateImageItem;
impl PartialSchema for ProductionStoryboardBatchGenerateImageItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBatchGenerateImageItem")
    }
}
impl ToSchema for ProductionStoryboardBatchGenerateImageItem {}

pub struct ProductionStoryboardBundleItem;
impl PartialSchema for ProductionStoryboardBundleItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionStoryboardBundleItem")
    }
}
impl ToSchema for ProductionStoryboardBundleItem {}

pub struct ProductionWorkbenchGenerateVideoUploadItem;
impl PartialSchema for ProductionWorkbenchGenerateVideoUploadItem {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProductionWorkbenchGenerateVideoUploadItem")
    }
}
impl ToSchema for ProductionWorkbenchGenerateVideoUploadItem {}

pub struct ProjectRow;
impl PartialSchema for ProjectRow {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ProjectRow")
    }
}
impl ToSchema for ProjectRow {}

pub struct ScriptAgentTypeV1;
impl PartialSchema for ScriptAgentTypeV1 {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptAgentTypeV1")
    }
}
impl ToSchema for ScriptAgentTypeV1 {}

pub struct ScriptBrief;
impl PartialSchema for ScriptBrief {
    fn schema() -> RefOr<Schema> {
        legacy_pick("ScriptBrief")
    }
}
impl ToSchema for ScriptBrief {}

use utoipa::openapi::schema::ComponentsBuilder;

pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {
    c = c.schema_from::<AboutCheckUpdateSource>();
    c = c.schema_from::<AssetGenTypeV1>();
    c = c.schema_from::<AssetImageListItem>();
    c = c.schema_from::<AssetImageRow>();
    c = c.schema_from::<AssetRow>();
    c = c.schema_from::<BatchAddScriptItem>();
    c = c.schema_from::<BatchGenerateImageItem>();
    c = c.schema_from::<BatchPolishAssetsItem>();
    c = c.schema_from::<CornerScapeAssetItem>();
    c = c.schema_from::<CornerScapeHistoryImage>();
    c = c.schema_from::<JobRow>();
    c = c.schema_from::<LegacyAssetsBatchGenerationDataItem>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiChildItem>();
    c = c.schema_from::<LegacyAssetsGetAssetsApiParentItem>();
    c = c.schema_from::<LegacyAssetsGetImageTempAsset>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataItem>();
    c = c.schema_from::<LegacyAssetsGetMaterialDataVideoItem>();
    c = c.schema_from::<LegacyDirectorManualDataSlot>();
    c = c.schema_from::<LegacyDirectorManualSlotRow>();
    c = c.schema_from::<LegacyDirectorManualStyleRow>();
    c = c.schema_from::<LegacyNovelAddNovelItem>();
    c = c.schema_from::<LegacyNovelEventRow>();
    c = c.schema_from::<LegacyNovelEventStateItem>();
    c = c.schema_from::<LegacyNovelGetNovelPageRow>();
    c = c.schema_from::<LegacyNovelIndexItem>();
    c = c.schema_from::<LegacyScriptRelatedAssetBrief>();
    c = c.schema_from::<LegacyScriptsGetScriptApiItem>();
    c = c.schema_from::<MemoryMarkdownBlock>();
    c = c.schema_from::<NovelEventWithChapters>();
    c = c.schema_from::<NovelRow>();
    c = c.schema_from::<ProductionAssetDataItem>();
    c = c.schema_from::<ProductionAssetImageStatus>();
    c = c.schema_from::<ProductionEditImageFlowStep>();
    c = c.schema_from::<ProductionEditImageFlowStepInput>();
    c = c.schema_from::<ProductionExportImageShotRef>();
    c = c.schema_from::<ProductionFlowAssetDerivativeItem>();
    c = c.schema_from::<ProductionFlowAssetItem>();
    c = c.schema_from::<ProductionFlowStoryboardItem>();
    c = c.schema_from::<ProductionStoryboardBatchAddInfoItem>();
    c = c.schema_from::<ProductionStoryboardBatchGenerateImageItem>();
    c = c.schema_from::<ProductionStoryboardBundleItem>();
    c = c.schema_from::<ProductionWorkbenchGenerateVideoUploadItem>();
    c = c.schema_from::<ProjectRow>();
    c = c.schema_from::<ScriptAgentTypeV1>();
    c = c.schema_from::<ScriptBrief>();
    c
}
