//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

use std::sync::OnceLock;

use utoipa::openapi::schema::Schema;
use utoipa::openapi::RefOr;

pub(super) fn legacy_component_map() -> &'static serde_json::Map<String, serde_json::Value> {
    static MAP: OnceLock<serde_json::Map<String, serde_json::Value>> = OnceLock::new();
    MAP.get_or_init(|| {
        serde_json::from_str(include_str!("../embedded/legacy_component_schemas.json"))
            .expect("legacy JSON")
    })
}

pub(super) fn legacy_pick(name: &str) -> RefOr<Schema> {
    let v = legacy_component_map()
        .get(name)
        .unwrap_or_else(|| panic!("missing legacy schema {name}"))
        .clone();
    serde_json::from_value(v).unwrap_or_else(|e| panic!("deserialize legacy schema {name}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_legacy_schema_deserializes() {
        for (k, _) in legacy_component_map() {
            let _: RefOr<Schema> = legacy_pick(k);
        }
    }
}
