//! `POST /api/v1/production/*` 路由表。

use axum::{routing::post, Router};

use crate::state::AppState;

use super::patch;
use super::workbench;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/v1/production/patch",
            post(patch::post_production_patch),
        )
        .route(
            "/api/v1/production/get-production-data",
            post(workbench::storyboard_ops::post_get_production_data),
        )
        .route(
            "/api/v1/production/get-flow-data",
            post(workbench::flow::post_get_flow_data),
        )
        .route(
            "/api/v1/production/save-flow-data",
            post(workbench::flow::post_save_flow_data),
        )
        .route(
            "/api/v1/production/workbench/generate-video",
            post(workbench::video::post_workbench_generate_video),
        )
        .route(
            "/api/v1/production/storyboard/polling-image",
            post(workbench::storyboard_ops::post_storyboard_polling_image),
        )
        .route(
            "/api/v1/production/export-image",
            post(workbench::storyboard_ops::post_export_image),
        )
        .route(
            "/api/v1/production/storyboard/batch-generate-image",
            post(workbench::storyboard_ops::post_storyboard_batch_generate_image),
        )
        .route(
            "/api/v1/production/workbench/get-video-list",
            post(workbench::video::post_workbench_get_video_list),
        )
        .route(
            "/api/v1/production/workbench/add-track",
            post(workbench::track::post_workbench_add_track),
        )
        .route(
            "/api/v1/production/workbench/delete-track",
            post(workbench::track::post_workbench_delete_track),
        )
        .route(
            "/api/v1/production/workbench/delete-video",
            post(workbench::track::post_workbench_delete_video),
        )
        .route(
            "/api/v1/production/workbench/select-video",
            post(workbench::track::post_workbench_select_video),
        )
        .route(
            "/api/v1/production/assets/batch-generate-assets-image",
            post(workbench::assets::post_assets_batch_generate_image),
        )
        .route(
            "/api/v1/production/assets/delete-assets-derivative",
            post(workbench::assets::post_assets_delete_derivative),
        )
        .route(
            "/api/v1/production/assets/get-assets-data",
            post(workbench::assets::post_assets_get_data),
        )
        .route(
            "/api/v1/production/assets/polling-image",
            post(workbench::assets::post_assets_polling_image),
        )
        .route(
            "/api/v1/production/assets/update-assets-url",
            post(workbench::assets::post_assets_update_url),
        )
        .route(
            "/api/v1/production/edit-image/get-image-flow",
            post(workbench::edit_image::post_edit_image_get_image_flow),
        )
        .route(
            "/api/v1/production/edit-image/get-image-default-model",
            post(workbench::edit_image::post_edit_image_get_image_default_model),
        )
        .route(
            "/api/v1/production/edit-image/save-image-flow",
            post(workbench::edit_image::post_edit_image_save_image_flow),
        )
        .route(
            "/api/v1/production/edit-image/update-image-flow",
            post(workbench::edit_image::post_edit_image_update_image_flow),
        )
        .route(
            "/api/v1/production/edit-image/generate-flow-image",
            post(workbench::edit_image::post_edit_image_generate_flow_image),
        )
        .route(
            "/api/v1/production/edit-image/upload-image",
            post(workbench::edit_image::post_edit_image_upload_image),
        )
        .route(
            "/api/v1/production/get-storyboard-data",
            post(workbench::storyboard::post_get_storyboard_data),
        )
        .route(
            "/api/v1/production/storyboard/add",
            post(workbench::storyboard::post_storyboard_add),
        )
        .route(
            "/api/v1/production/storyboard/batch-add-info",
            post(workbench::storyboard::post_storyboard_batch_add_info),
        )
        .route(
            "/api/v1/production/storyboard/down-preview-image",
            post(workbench::storyboard::post_storyboard_down_preview_image),
        )
        .route(
            "/api/v1/production/storyboard/edit-info",
            post(workbench::storyboard::post_storyboard_edit_info),
        )
        .route(
            "/api/v1/production/storyboard/get-data",
            post(workbench::storyboard::post_storyboard_get_data),
        )
        .route(
            "/api/v1/production/storyboard/preview-image",
            post(workbench::storyboard::post_storyboard_preview_image),
        )
        .route(
            "/api/v1/production/storyboard/remove-frame",
            post(workbench::storyboard::post_storyboard_remove_frame),
        )
        .route(
            "/api/v1/production/storyboard/update-url",
            post(workbench::storyboard::post_storyboard_update_url),
        )
        .route(
            "/api/v1/production/workbench/generate-video-prompt",
            post(workbench::meta::post_workbench_generate_video_prompt),
        )
        .route(
            "/api/v1/production/workbench/get-generate-data",
            post(workbench::meta::post_workbench_get_generate_data),
        )
        .route(
            "/api/v1/production/workbench/get-video-model-detail",
            post(workbench::meta::post_workbench_get_video_model_detail),
        )
}
