part of '../../../../home_page.dart';

extension _HomePageProjectEditorAssetsWorkbench on _HomePageState {
  Future<void> _openAssetWorkbenchDialog({
    required BuildContext ctx,
    required StateSetter setDialogState,
    required String token,
    required ProjectRow p,
    required List<ScriptBrief> scriptList,
    required List<ListAssetsResponse?> assetsRef,
    required List<ListAssetsResponse?> assetsForScriptRef,
    required List<int?> assetsFilterScriptNumericId,
    required List<bool> assetsBusy,
    required Future<void> Function() reloadAssetsAndStats,
  }) async {
    await openProjectAssetsWorkbenchDialog(
      ctx: ctx,
      setDialogState: setDialogState,
      token: token,
      project: p,
      scriptList: scriptList,
      assetsRef: assetsRef,
      assetsForScriptRef: assetsForScriptRef,
      assetsFilterScriptNumericId: assetsFilterScriptNumericId,
      assetsBusy: assetsBusy,
      reloadAssetsAndStats: reloadAssetsAndStats,
      onCreateAsset: (dialogCtx) => _openCreateAssetDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      onEditAsset: (dialogCtx) => _openEditAssetDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      onDeleteAsset: (dialogCtx) => _openDeleteAssetDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      onFilterAssets: (dialogCtx) => _openAssetFilterDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsForScriptRef: assetsForScriptRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsBusy: assetsBusy,
      ),
      onLinkAsset: (dialogCtx) => openProjectAssetLinkDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
        unlink: false,
      ),
      onUnlinkAsset: (dialogCtx) => openProjectAssetLinkDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
        unlink: true,
      ),
      onUploadEditImage: (dialogCtx) => openProjectAssetEditImageUploadDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        scriptList: scriptList,
        assetsBusy: assetsBusy,
      ),
      onUploadClip: (dialogCtx) => openProjectAssetClipUploadDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      onOpenImagesWorkbench:
          (dialogCtx, preferredAssetNumericId) =>
              _openAssetImagesWorkbenchDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
        preferredAssetNumericId: preferredAssetNumericId,
      ),
      onOpenGenerationWorkbench:
          (dialogCtx, preferredAssetNumericId) =>
          openAssetGenerationWorkbenchDialog(
            ctx: dialogCtx,
            setDialogState: setDialogState,
            token: token,
            project: p,
            scriptList: scriptList,
            assetsRef: assetsRef,
            assetsForScriptRef: assetsForScriptRef,
            assetsFilterScriptNumericId: assetsFilterScriptNumericId,
            assetsBusy: assetsBusy,
            reloadAssetsAndStats: reloadAssetsAndStats,
            preferredAssetNumericId: preferredAssetNumericId,
          ),
      onOpenHistoryWorkbench:
          (dialogCtx, preferredAssetNumericId) =>
              openCornerScapeWorkbenchDialog(
        ctx: dialogCtx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        assetsBusy: assetsBusy,
        preferredAssetNumericId: preferredAssetNumericId,
      ),
    );
  }
}
