#!/usr/bin/env python3
"""Generate `backend/src/openapi_spec/legacy_components/` from `embedded/legacy_component_schemas.json`.

Each OpenAPI component becomes a ZST + `PartialSchema`/`ToSchema` backed by the embedded JSON
(serde into utoipa's `Schema`), so the merge pipeline no longer injects raw JSON in `merge.rs`.

**End goal (utoipa-only):** every component schema should live as Rust `#[derive(ToSchema)]` (or domain
`OpenApi` merges). When `legacy_component_schemas.json` has **no keys**, delete this script and the
`legacy_components/` output, and remove the `legacy_components` merge from `openapi_spec::combined_openapi`.

Run from repo root after updating the embedded JSON (e.g. from `extract_openapi_rust_sources.py`):

  python3 scripts/gen_legacy_utoipa_registry.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "backend/src/openapi_spec/embedded/legacy_component_schemas.json"
OUT_DIR = ROOT / "backend/src/openapi_spec/legacy_components"
BATCH_SIZE = 45


def _normalize_const(obj: object) -> None:
    """In-place: single-property `const` -> `type` + `enum` (utoipa-compatible)."""
    if isinstance(obj, dict):
        if (
            len(obj) <= 4
            and "const" in obj
            and "type" not in obj
            and "enum" not in obj
        ):
            c = obj.pop("const")
            obj["type"] = (
                "string"
                if isinstance(c, str)
                else "number"
                if isinstance(c, (int, float))
                else "boolean"
                if isinstance(c, bool)
                else "string"
            )
            obj["enum"] = [c]
        for v in obj.values():
            _normalize_const(v)
    elif isinstance(obj, list):
        for v in obj:
            _normalize_const(v)


def _load_normalized() -> dict[str, object]:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("legacy JSON must be an object")
    _normalize_const(data)
    return data


def _write_inline() -> None:
    content = r"""//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

use std::sync::OnceLock;

use utoipa::openapi::schema::Schema;
use utoipa::openapi::RefOr;

pub(super) fn legacy_component_map() -> &'static serde_json::Map<String, serde_json::Value> {
    static MAP: OnceLock<serde_json::Map<String, serde_json::Value>> = OnceLock::new();
    MAP.get_or_init(|| {
        serde_json::from_str(include_str!("../embedded/legacy_component_schemas.json"))
            .expect("legacy JSON")
    })
}

pub(super) fn legacy_pick(name: &str) -> RefOr<Schema> {
    let v = legacy_component_map()
        .get(name)
        .unwrap_or_else(|| panic!("missing legacy schema {name}"))
        .clone();
    serde_json::from_value(v).unwrap_or_else(|e| panic!("deserialize legacy schema {name}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_legacy_schema_deserializes() {
        for (k, _) in legacy_component_map() {
            let _: RefOr<Schema> = legacy_pick(k);
        }
    }
}
"""
    (OUT_DIR / "inline.rs").write_text(content, encoding="utf-8")


def _rust_ident(name: str) -> str:
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
        raise SystemExit(f"invalid schema name for Rust: {name!r}")
    return name


def _write_batch(batch_idx: int, names: list[str]) -> None:
    lines = [
        "//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.",
        "",
        "#![allow(dead_code)]",
        "",
        "use utoipa::{PartialSchema, ToSchema};",
        "use utoipa::openapi::{RefOr, schema::Schema};",
        "",
        "use super::inline::legacy_pick;",
        "",
    ]
    for n in names:
        ident = _rust_ident(n)
        lines.append(f"pub struct {ident};")
        lines.append(f"impl PartialSchema for {ident} {{")
        lines.append("    fn schema() -> RefOr<Schema> {")
        lines.append(f'        legacy_pick("{n}")')
        lines.append("    }")
        lines.append("}")
        lines.append(f"impl ToSchema for {ident} {{}}")
        lines.append("")

    lines.append("use utoipa::openapi::schema::ComponentsBuilder;")
    lines.append("")
    lines.append("pub(super) fn register_schemas(mut c: ComponentsBuilder) -> ComponentsBuilder {")
    for n in names:
        ident = _rust_ident(n)
        lines.append(f"    c = c.schema_from::<{ident}>();")
    lines.append("    c")
    lines.append("}")
    lines.append("")

    (OUT_DIR / f"batch{batch_idx:02d}.rs").write_text("\n".join(lines), encoding="utf-8")


def _write_mod(num_batches: int) -> None:
    mods = "\n".join(f"mod batch{i:02d};" for i in range(num_batches))
    regs = "\n".join(
        f"    c = batch{i:02d}::register_schemas(c);" for i in range(num_batches)
    )
    content = f"""//! AUTO-GENERATED by `scripts/gen_legacy_utoipa_registry.py`. Do not edit.

{mods}
mod inline;

use utoipa::openapi::{{OpenApi, OpenApiBuilder, Paths}};
use utoipa::openapi::schema::ComponentsBuilder;

/// All legacy component schemas as utoipa [`utoipa::ToSchema`] registrations (JSON-backed).
pub fn merged_legacy_components_openapi() -> OpenApi {{
    let mut c = ComponentsBuilder::new();
{regs}
    OpenApiBuilder::new()
        .components(Some(c.build()))
        .paths(Paths::new())
        .build()
}}
"""
    (OUT_DIR / "mod.rs").write_text(content, encoding="utf-8")


def main() -> None:
    if not JSON_PATH.is_file():
        raise SystemExit(f"missing {{JSON_PATH}}")
    data = _load_normalized()
    names = sorted(data.keys())
    if not names:
        raise SystemExit("no schemas in legacy JSON")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Persist normalized JSON (const -> enum, etc.) for humans and smaller diffs.
    JSON_PATH.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    _write_inline()

    batches: list[list[str]] = []
    for i in range(0, len(names), BATCH_SIZE):
        batches.append(names[i : i + BATCH_SIZE])

    for i, chunk in enumerate(batches):
        _write_batch(i, chunk)

    _write_mod(len(batches))
    print(f"Wrote {len(names)} schemas in {len(batches)} batches under {OUT_DIR}")


if __name__ == "__main__":
    main()
