part of '../../../home_page.dart';

extension _HomePageProjectEditorAssets on _HomePageState {
  Widget _buildProjectAssetsSection({
    required BuildContext ctx,
    required StateSetter setDialogState,
    required String token,
    required ProjectRow p,
    required List<ScriptBrief> scriptList,
    required List<ListAssetsResponse?> assetsRef,
    required List<ListAssetsResponse?> assetsForScriptRef,
    required List<int?> assetsFilterScriptNumericId,
    required List<bool> assetsLoading,
    required List<bool> assetsScriptFilterLoading,
    required List<bool> assetsBusy,
    required Future<void> Function() reloadAssetsAndStats,
  }) {
    return buildProjectAssetsSection(
      ctx: ctx,
      setDialogState: setDialogState,
      token: token,
      project: p,
      scriptList: scriptList,
      assetsRef: assetsRef,
      assetsForScriptRef: assetsForScriptRef,
      assetsFilterScriptNumericId: assetsFilterScriptNumericId,
      assetsLoading: assetsLoading,
      assetsScriptFilterLoading: assetsScriptFilterLoading,
      assetsBusy: assetsBusy,
      reloadAssetsAndStats: reloadAssetsAndStats,
      openWorkbench: () => _openAssetWorkbenchDialog(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsForScriptRef: assetsForScriptRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildImagesSection: () => _buildProjectAssetsImagesCompatibilitySection(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildPrimaryActions: () => _buildProjectAssetsPrimaryActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildRelationActions: () => _buildProjectAssetsRelationActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildQueryActions: () => _buildProjectAssetsQueryCompatibilityActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
    );
  }
}
