part of '../../../home_page.dart';

extension _HomePageProjectEditorAssets on _HomePageState {
  Widget _buildProjectAssetsSection({
    required BuildContext ctx,
    required StateSetter setDialogState,
    required String token,
    required ProjectRow p,
    required List<ScriptBrief> scriptList,
    required List<ListAssetsResponse?> assetsRef,
    required List<ListAssetsResponse?> assetsForScriptRef,
    required List<int?> assetsFilterScriptNumericId,
    required List<bool> assetsLoading,
    required List<bool> assetsScriptFilterLoading,
    required List<bool> assetsBusy,
    required Future<void> Function() reloadAssetsAndStats,
  }) {
    return buildProjectAssetsSection(
      ctx: ctx,
      setDialogState: setDialogState,
      token: token,
      project: p,
      scriptList: scriptList,
      assetsRef: assetsRef,
      assetsForScriptRef: assetsForScriptRef,
      assetsFilterScriptNumericId: assetsFilterScriptNumericId,
      assetsLoading: assetsLoading,
      assetsScriptFilterLoading: assetsScriptFilterLoading,
      assetsBusy: assetsBusy,
      reloadAssetsAndStats: reloadAssetsAndStats,
      openWorkbench: () => openProjectAssetsWorkbenchDialog(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        project: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsForScriptRef: assetsForScriptRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
        onCreateAsset: (dialogCtx) => _openCreateAssetDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          p: p,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
        ),
        onEditAsset: (dialogCtx) => _openEditAssetDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          p: p,
          assetsRef: assetsRef,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
        ),
        onDeleteAsset: (dialogCtx) => _openDeleteAssetDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          p: p,
          assetsRef: assetsRef,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
        ),
        onFilterAssets: (dialogCtx) => _openAssetFilterDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          p: p,
          scriptList: scriptList,
          assetsRef: assetsRef,
          assetsForScriptRef: assetsForScriptRef,
          assetsFilterScriptNumericId: assetsFilterScriptNumericId,
          assetsBusy: assetsBusy,
        ),
        onLinkAsset: (dialogCtx) => openProjectAssetLinkDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          project: p,
          scriptList: scriptList,
          assetsRef: assetsRef,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
          unlink: false,
        ),
        onUnlinkAsset: (dialogCtx) => openProjectAssetLinkDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          project: p,
          scriptList: scriptList,
          assetsRef: assetsRef,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
          unlink: true,
        ),
        onUploadEditImage: (dialogCtx) => openProjectAssetEditImageUploadDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          project: p,
          scriptList: scriptList,
          assetsBusy: assetsBusy,
        ),
        onUploadClip: (dialogCtx) => openProjectAssetClipUploadDialog(
          ctx: dialogCtx,
          setDialogState: setDialogState,
          token: token,
          project: p,
          assetsBusy: assetsBusy,
          reloadAssetsAndStats: reloadAssetsAndStats,
        ),
        onOpenImagesWorkbench:
            (dialogCtx, preferredAssetNumericId) =>
                openAssetImagesWorkbenchDialog(
                  ctx: dialogCtx,
                  setDialogState: setDialogState,
                  token: token,
                  project: p,
                  assetsRef: assetsRef,
                  assetsBusy: assetsBusy,
                  reloadAssetsAndStats: reloadAssetsAndStats,
                  preferredAssetNumericId: preferredAssetNumericId,
                ),
        onOpenGenerationWorkbench:
            (dialogCtx, preferredAssetNumericId) =>
                openAssetGenerationWorkbenchDialog(
                  ctx: dialogCtx,
                  setDialogState: setDialogState,
                  token: token,
                  project: p,
                  scriptList: scriptList,
                  assetsRef: assetsRef,
                  assetsForScriptRef: assetsForScriptRef,
                  assetsFilterScriptNumericId: assetsFilterScriptNumericId,
                  assetsBusy: assetsBusy,
                  reloadAssetsAndStats: reloadAssetsAndStats,
                  preferredAssetNumericId: preferredAssetNumericId,
                ),
        onOpenHistoryWorkbench:
            (dialogCtx, preferredAssetNumericId) =>
                openCornerScapeWorkbenchDialog(
                  ctx: dialogCtx,
                  setDialogState: setDialogState,
                  token: token,
                  project: p,
                  assetsBusy: assetsBusy,
                  preferredAssetNumericId: preferredAssetNumericId,
                ),
      ),
      buildImagesSection: () => _buildProjectAssetsImagesCompatibilitySection(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildPrimaryActions: () => _buildProjectAssetsPrimaryActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildRelationActions: () => _buildProjectAssetsRelationActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        scriptList: scriptList,
        assetsRef: assetsRef,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
      buildQueryActions: () => _buildProjectAssetsQueryCompatibilityActions(
        ctx: ctx,
        setDialogState: setDialogState,
        token: token,
        p: p,
        assetsRef: assetsRef,
        assetsFilterScriptNumericId: assetsFilterScriptNumericId,
        assetsLoading: assetsLoading,
        assetsScriptFilterLoading: assetsScriptFilterLoading,
        assetsBusy: assetsBusy,
        reloadAssetsAndStats: reloadAssetsAndStats,
      ),
    );
  }
}
